package org.fbi.gwk.repository.model.gwk;

import java.math.BigDecimal;

public class CpSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.SEQNAME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String seqname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.MINVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private Long minvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.MAXVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private Long maxvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.CYCLE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.STEPVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private BigDecimal stepvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.CACHE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private BigDecimal cache;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.YEAR
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.CP_SEQUENCE.CURVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private Long curvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.SEQNAME
     *
     * @return the value of GWK.CP_SEQUENCE.SEQNAME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getSeqname() {
        return seqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.SEQNAME
     *
     * @param seqname the value for GWK.CP_SEQUENCE.SEQNAME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setSeqname(String seqname) {
        this.seqname = seqname == null ? null : seqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.MINVALUE
     *
     * @return the value of GWK.CP_SEQUENCE.MINVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Long getMinvalue() {
        return minvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.MINVALUE
     *
     * @param minvalue the value for GWK.CP_SEQUENCE.MINVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setMinvalue(Long minvalue) {
        this.minvalue = minvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.MAXVALUE
     *
     * @return the value of GWK.CP_SEQUENCE.MAXVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Long getMaxvalue() {
        return maxvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.MAXVALUE
     *
     * @param maxvalue the value for GWK.CP_SEQUENCE.MAXVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setMaxvalue(Long maxvalue) {
        this.maxvalue = maxvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.CYCLE
     *
     * @return the value of GWK.CP_SEQUENCE.CYCLE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.CYCLE
     *
     * @param cycle the value for GWK.CP_SEQUENCE.CYCLE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.STEPVALUE
     *
     * @return the value of GWK.CP_SEQUENCE.STEPVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public BigDecimal getStepvalue() {
        return stepvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.STEPVALUE
     *
     * @param stepvalue the value for GWK.CP_SEQUENCE.STEPVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setStepvalue(BigDecimal stepvalue) {
        this.stepvalue = stepvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.CACHE
     *
     * @return the value of GWK.CP_SEQUENCE.CACHE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public BigDecimal getCache() {
        return cache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.CACHE
     *
     * @param cache the value for GWK.CP_SEQUENCE.CACHE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCache(BigDecimal cache) {
        this.cache = cache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.YEAR
     *
     * @return the value of GWK.CP_SEQUENCE.YEAR
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.YEAR
     *
     * @param year the value for GWK.CP_SEQUENCE.YEAR
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.CP_SEQUENCE.CURVALUE
     *
     * @return the value of GWK.CP_SEQUENCE.CURVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Long getCurvalue() {
        return curvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.CP_SEQUENCE.CURVALUE
     *
     * @param curvalue the value for GWK.CP_SEQUENCE.CURVALUE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCurvalue(Long curvalue) {
        this.curvalue = curvalue;
    }
}