package org.fbi.gwk.repository.model.gwk;

import java.util.Date;

public class LsBdgagencyH {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.AREACODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.NAME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.GUID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.LEVELNO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String levelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.SUPERCODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String supercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.ISLEAF
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.VERSION
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.ACTION
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.ACTIONDATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String actiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.ACTIONTIME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String actiontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.REMARK
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.OPERID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.LS_BDGAGENCY_H.OPERDATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private Date operdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.AREACODE
     *
     * @return the value of GWK.LS_BDGAGENCY_H.AREACODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.AREACODE
     *
     * @param areacode the value for GWK.LS_BDGAGENCY_H.AREACODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.CODE
     *
     * @return the value of GWK.LS_BDGAGENCY_H.CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.CODE
     *
     * @param code the value for GWK.LS_BDGAGENCY_H.CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.NAME
     *
     * @return the value of GWK.LS_BDGAGENCY_H.NAME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.NAME
     *
     * @param name the value for GWK.LS_BDGAGENCY_H.NAME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.GUID
     *
     * @return the value of GWK.LS_BDGAGENCY_H.GUID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.GUID
     *
     * @param guid the value for GWK.LS_BDGAGENCY_H.GUID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.LEVELNO
     *
     * @return the value of GWK.LS_BDGAGENCY_H.LEVELNO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.LEVELNO
     *
     * @param levelno the value for GWK.LS_BDGAGENCY_H.LEVELNO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setLevelno(String levelno) {
        this.levelno = levelno == null ? null : levelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.SUPERCODE
     *
     * @return the value of GWK.LS_BDGAGENCY_H.SUPERCODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getSupercode() {
        return supercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.SUPERCODE
     *
     * @param supercode the value for GWK.LS_BDGAGENCY_H.SUPERCODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setSupercode(String supercode) {
        this.supercode = supercode == null ? null : supercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.ISLEAF
     *
     * @return the value of GWK.LS_BDGAGENCY_H.ISLEAF
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.ISLEAF
     *
     * @param isleaf the value for GWK.LS_BDGAGENCY_H.ISLEAF
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.VERSION
     *
     * @return the value of GWK.LS_BDGAGENCY_H.VERSION
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.VERSION
     *
     * @param version the value for GWK.LS_BDGAGENCY_H.VERSION
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.ACTION
     *
     * @return the value of GWK.LS_BDGAGENCY_H.ACTION
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.ACTION
     *
     * @param action the value for GWK.LS_BDGAGENCY_H.ACTION
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.ACTIONDATE
     *
     * @return the value of GWK.LS_BDGAGENCY_H.ACTIONDATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getActiondate() {
        return actiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.ACTIONDATE
     *
     * @param actiondate the value for GWK.LS_BDGAGENCY_H.ACTIONDATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setActiondate(String actiondate) {
        this.actiondate = actiondate == null ? null : actiondate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.ACTIONTIME
     *
     * @return the value of GWK.LS_BDGAGENCY_H.ACTIONTIME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.ACTIONTIME
     *
     * @param actiontime the value for GWK.LS_BDGAGENCY_H.ACTIONTIME
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setActiontime(String actiontime) {
        this.actiontime = actiontime == null ? null : actiontime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.REMARK
     *
     * @return the value of GWK.LS_BDGAGENCY_H.REMARK
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.REMARK
     *
     * @param remark the value for GWK.LS_BDGAGENCY_H.REMARK
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.OPERID
     *
     * @return the value of GWK.LS_BDGAGENCY_H.OPERID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.OPERID
     *
     * @param operid the value for GWK.LS_BDGAGENCY_H.OPERID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.LS_BDGAGENCY_H.OPERDATE
     *
     * @return the value of GWK.LS_BDGAGENCY_H.OPERDATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Date getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.LS_BDGAGENCY_H.OPERDATE
     *
     * @param operdate the value for GWK.LS_BDGAGENCY_H.OPERDATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOperdate(Date operdate) {
        this.operdate = operdate;
    }
}