package org.fbi.gwk.repository.model.gwk;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LsCardbaseinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public LsCardbaseinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccountIsNull() {
            addCriterion("ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("ACCOUNT =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("ACCOUNT <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("ACCOUNT >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("ACCOUNT <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("ACCOUNT like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("ACCOUNT not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("ACCOUNT in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("ACCOUNT not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("ACCOUNT between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andCardnameIsNull() {
            addCriterion("CARDNAME is null");
            return (Criteria) this;
        }

        public Criteria andCardnameIsNotNull() {
            addCriterion("CARDNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCardnameEqualTo(String value) {
            addCriterion("CARDNAME =", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotEqualTo(String value) {
            addCriterion("CARDNAME <>", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameGreaterThan(String value) {
            addCriterion("CARDNAME >", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameGreaterThanOrEqualTo(String value) {
            addCriterion("CARDNAME >=", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLessThan(String value) {
            addCriterion("CARDNAME <", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLessThanOrEqualTo(String value) {
            addCriterion("CARDNAME <=", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLike(String value) {
            addCriterion("CARDNAME like", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotLike(String value) {
            addCriterion("CARDNAME not like", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameIn(List<String> values) {
            addCriterion("CARDNAME in", values, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotIn(List<String> values) {
            addCriterion("CARDNAME not in", values, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameBetween(String value1, String value2) {
            addCriterion("CARDNAME between", value1, value2, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotBetween(String value1, String value2) {
            addCriterion("CARDNAME not between", value1, value2, "cardname");
            return (Criteria) this;
        }

        public Criteria andBdgagencyIsNull() {
            addCriterion("BDGAGENCY is null");
            return (Criteria) this;
        }

        public Criteria andBdgagencyIsNotNull() {
            addCriterion("BDGAGENCY is not null");
            return (Criteria) this;
        }

        public Criteria andBdgagencyEqualTo(String value) {
            addCriterion("BDGAGENCY =", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyNotEqualTo(String value) {
            addCriterion("BDGAGENCY <>", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyGreaterThan(String value) {
            addCriterion("BDGAGENCY >", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyGreaterThanOrEqualTo(String value) {
            addCriterion("BDGAGENCY >=", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyLessThan(String value) {
            addCriterion("BDGAGENCY <", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyLessThanOrEqualTo(String value) {
            addCriterion("BDGAGENCY <=", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyLike(String value) {
            addCriterion("BDGAGENCY like", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyNotLike(String value) {
            addCriterion("BDGAGENCY not like", value, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyIn(List<String> values) {
            addCriterion("BDGAGENCY in", values, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyNotIn(List<String> values) {
            addCriterion("BDGAGENCY not in", values, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyBetween(String value1, String value2) {
            addCriterion("BDGAGENCY between", value1, value2, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andBdgagencyNotBetween(String value1, String value2) {
            addCriterion("BDGAGENCY not between", value1, value2, "bdgagency");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameIsNull() {
            addCriterion("GATHERINGBANKACCTNAME is null");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameIsNotNull() {
            addCriterion("GATHERINGBANKACCTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTNAME =", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameNotEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTNAME <>", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameGreaterThan(String value) {
            addCriterion("GATHERINGBANKACCTNAME >", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameGreaterThanOrEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTNAME >=", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameLessThan(String value) {
            addCriterion("GATHERINGBANKACCTNAME <", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameLessThanOrEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTNAME <=", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameLike(String value) {
            addCriterion("GATHERINGBANKACCTNAME like", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameNotLike(String value) {
            addCriterion("GATHERINGBANKACCTNAME not like", value, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameIn(List<String> values) {
            addCriterion("GATHERINGBANKACCTNAME in", values, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameNotIn(List<String> values) {
            addCriterion("GATHERINGBANKACCTNAME not in", values, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameBetween(String value1, String value2) {
            addCriterion("GATHERINGBANKACCTNAME between", value1, value2, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctnameNotBetween(String value1, String value2) {
            addCriterion("GATHERINGBANKACCTNAME not between", value1, value2, "gatheringbankacctname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameIsNull() {
            addCriterion("GATHERINGBANKNAME is null");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameIsNotNull() {
            addCriterion("GATHERINGBANKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameEqualTo(String value) {
            addCriterion("GATHERINGBANKNAME =", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameNotEqualTo(String value) {
            addCriterion("GATHERINGBANKNAME <>", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameGreaterThan(String value) {
            addCriterion("GATHERINGBANKNAME >", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameGreaterThanOrEqualTo(String value) {
            addCriterion("GATHERINGBANKNAME >=", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameLessThan(String value) {
            addCriterion("GATHERINGBANKNAME <", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameLessThanOrEqualTo(String value) {
            addCriterion("GATHERINGBANKNAME <=", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameLike(String value) {
            addCriterion("GATHERINGBANKNAME like", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameNotLike(String value) {
            addCriterion("GATHERINGBANKNAME not like", value, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameIn(List<String> values) {
            addCriterion("GATHERINGBANKNAME in", values, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameNotIn(List<String> values) {
            addCriterion("GATHERINGBANKNAME not in", values, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameBetween(String value1, String value2) {
            addCriterion("GATHERINGBANKNAME between", value1, value2, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbanknameNotBetween(String value1, String value2) {
            addCriterion("GATHERINGBANKNAME not between", value1, value2, "gatheringbankname");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeIsNull() {
            addCriterion("GATHERINGBANKACCTCODE is null");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeIsNotNull() {
            addCriterion("GATHERINGBANKACCTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTCODE =", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeNotEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTCODE <>", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeGreaterThan(String value) {
            addCriterion("GATHERINGBANKACCTCODE >", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeGreaterThanOrEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTCODE >=", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeLessThan(String value) {
            addCriterion("GATHERINGBANKACCTCODE <", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeLessThanOrEqualTo(String value) {
            addCriterion("GATHERINGBANKACCTCODE <=", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeLike(String value) {
            addCriterion("GATHERINGBANKACCTCODE like", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeNotLike(String value) {
            addCriterion("GATHERINGBANKACCTCODE not like", value, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeIn(List<String> values) {
            addCriterion("GATHERINGBANKACCTCODE in", values, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeNotIn(List<String> values) {
            addCriterion("GATHERINGBANKACCTCODE not in", values, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeBetween(String value1, String value2) {
            addCriterion("GATHERINGBANKACCTCODE between", value1, value2, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andGatheringbankacctcodeNotBetween(String value1, String value2) {
            addCriterion("GATHERINGBANKACCTCODE not between", value1, value2, "gatheringbankacctcode");
            return (Criteria) this;
        }

        public Criteria andIdnumberIsNull() {
            addCriterion("IDNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andIdnumberIsNotNull() {
            addCriterion("IDNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andIdnumberEqualTo(String value) {
            addCriterion("IDNUMBER =", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotEqualTo(String value) {
            addCriterion("IDNUMBER <>", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberGreaterThan(String value) {
            addCriterion("IDNUMBER >", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberGreaterThanOrEqualTo(String value) {
            addCriterion("IDNUMBER >=", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLessThan(String value) {
            addCriterion("IDNUMBER <", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLessThanOrEqualTo(String value) {
            addCriterion("IDNUMBER <=", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLike(String value) {
            addCriterion("IDNUMBER like", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotLike(String value) {
            addCriterion("IDNUMBER not like", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberIn(List<String> values) {
            addCriterion("IDNUMBER in", values, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotIn(List<String> values) {
            addCriterion("IDNUMBER not in", values, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberBetween(String value1, String value2) {
            addCriterion("IDNUMBER between", value1, value2, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotBetween(String value1, String value2) {
            addCriterion("IDNUMBER not between", value1, value2, "idnumber");
            return (Criteria) this;
        }

        public Criteria andDigestIsNull() {
            addCriterion("DIGEST is null");
            return (Criteria) this;
        }

        public Criteria andDigestIsNotNull() {
            addCriterion("DIGEST is not null");
            return (Criteria) this;
        }

        public Criteria andDigestEqualTo(String value) {
            addCriterion("DIGEST =", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotEqualTo(String value) {
            addCriterion("DIGEST <>", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThan(String value) {
            addCriterion("DIGEST >", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThanOrEqualTo(String value) {
            addCriterion("DIGEST >=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThan(String value) {
            addCriterion("DIGEST <", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThanOrEqualTo(String value) {
            addCriterion("DIGEST <=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLike(String value) {
            addCriterion("DIGEST like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotLike(String value) {
            addCriterion("DIGEST not like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestIn(List<String> values) {
            addCriterion("DIGEST in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotIn(List<String> values) {
            addCriterion("DIGEST not in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestBetween(String value1, String value2) {
            addCriterion("DIGEST between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotBetween(String value1, String value2) {
            addCriterion("DIGEST not between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("BANK is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("BANK is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(Long value) {
            addCriterion("BANK =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(Long value) {
            addCriterion("BANK <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(Long value) {
            addCriterion("BANK >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(Long value) {
            addCriterion("BANK >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(Long value) {
            addCriterion("BANK <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(Long value) {
            addCriterion("BANK <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<Long> values) {
            addCriterion("BANK in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<Long> values) {
            addCriterion("BANK not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(Long value1, Long value2) {
            addCriterion("BANK between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(Long value1, Long value2) {
            addCriterion("BANK not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(String value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(String value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(String value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(String value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(String value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLike(String value) {
            addCriterion("CREATEDATE like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotLike(String value) {
            addCriterion("CREATEDATE not like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<String> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<String> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(String value1, String value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(String value1, String value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(String value) {
            addCriterion("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(String value) {
            addCriterion("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(String value) {
            addCriterion("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(String value) {
            addCriterion("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(String value) {
            addCriterion("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLike(String value) {
            addCriterion("STARTDATE like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotLike(String value) {
            addCriterion("STARTDATE not like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<String> values) {
            addCriterion("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<String> values) {
            addCriterion("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(String value1, String value2) {
            addCriterion("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(String value1, String value2) {
            addCriterion("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(String value) {
            addCriterion("ENDDATE =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(String value) {
            addCriterion("ENDDATE <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(String value) {
            addCriterion("ENDDATE >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("ENDDATE >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(String value) {
            addCriterion("ENDDATE <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(String value) {
            addCriterion("ENDDATE <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLike(String value) {
            addCriterion("ENDDATE like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotLike(String value) {
            addCriterion("ENDDATE not like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<String> values) {
            addCriterion("ENDDATE in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<String> values) {
            addCriterion("ENDDATE not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(String value1, String value2) {
            addCriterion("ENDDATE between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(String value1, String value2) {
            addCriterion("ENDDATE not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andActionIsNull() {
            addCriterion("ACTION is null");
            return (Criteria) this;
        }

        public Criteria andActionIsNotNull() {
            addCriterion("ACTION is not null");
            return (Criteria) this;
        }

        public Criteria andActionEqualTo(String value) {
            addCriterion("ACTION =", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotEqualTo(String value) {
            addCriterion("ACTION <>", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThan(String value) {
            addCriterion("ACTION >", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThanOrEqualTo(String value) {
            addCriterion("ACTION >=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThan(String value) {
            addCriterion("ACTION <", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThanOrEqualTo(String value) {
            addCriterion("ACTION <=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLike(String value) {
            addCriterion("ACTION like", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotLike(String value) {
            addCriterion("ACTION not like", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionIn(List<String> values) {
            addCriterion("ACTION in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotIn(List<String> values) {
            addCriterion("ACTION not in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionBetween(String value1, String value2) {
            addCriterion("ACTION between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotBetween(String value1, String value2) {
            addCriterion("ACTION not between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(Date value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(Date value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(Date value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(Date value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(Date value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<Date> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<Date> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(Date value1, Date value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(Date value1, Date value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andSentflagIsNull() {
            addCriterion("SENTFLAG is null");
            return (Criteria) this;
        }

        public Criteria andSentflagIsNotNull() {
            addCriterion("SENTFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSentflagEqualTo(String value) {
            addCriterion("SENTFLAG =", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagNotEqualTo(String value) {
            addCriterion("SENTFLAG <>", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagGreaterThan(String value) {
            addCriterion("SENTFLAG >", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagGreaterThanOrEqualTo(String value) {
            addCriterion("SENTFLAG >=", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagLessThan(String value) {
            addCriterion("SENTFLAG <", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagLessThanOrEqualTo(String value) {
            addCriterion("SENTFLAG <=", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagLike(String value) {
            addCriterion("SENTFLAG like", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagNotLike(String value) {
            addCriterion("SENTFLAG not like", value, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagIn(List<String> values) {
            addCriterion("SENTFLAG in", values, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagNotIn(List<String> values) {
            addCriterion("SENTFLAG not in", values, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagBetween(String value1, String value2) {
            addCriterion("SENTFLAG between", value1, value2, "sentflag");
            return (Criteria) this;
        }

        public Criteria andSentflagNotBetween(String value1, String value2) {
            addCriterion("SENTFLAG not between", value1, value2, "sentflag");
            return (Criteria) this;
        }

        public Criteria andTxlogIsNull() {
            addCriterion("TXLOG is null");
            return (Criteria) this;
        }

        public Criteria andTxlogIsNotNull() {
            addCriterion("TXLOG is not null");
            return (Criteria) this;
        }

        public Criteria andTxlogEqualTo(String value) {
            addCriterion("TXLOG =", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotEqualTo(String value) {
            addCriterion("TXLOG <>", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogGreaterThan(String value) {
            addCriterion("TXLOG >", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogGreaterThanOrEqualTo(String value) {
            addCriterion("TXLOG >=", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogLessThan(String value) {
            addCriterion("TXLOG <", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogLessThanOrEqualTo(String value) {
            addCriterion("TXLOG <=", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogLike(String value) {
            addCriterion("TXLOG like", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotLike(String value) {
            addCriterion("TXLOG not like", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogIn(List<String> values) {
            addCriterion("TXLOG in", values, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotIn(List<String> values) {
            addCriterion("TXLOG not in", values, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogBetween(String value1, String value2) {
            addCriterion("TXLOG between", value1, value2, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotBetween(String value1, String value2) {
            addCriterion("TXLOG not between", value1, value2, "txlog");
            return (Criteria) this;
        }

        public Criteria andOdsbdateIsNull() {
            addCriterion("ODSBDATE is null");
            return (Criteria) this;
        }

        public Criteria andOdsbdateIsNotNull() {
            addCriterion("ODSBDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOdsbdateEqualTo(String value) {
            addCriterion("ODSBDATE =", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotEqualTo(String value) {
            addCriterion("ODSBDATE <>", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateGreaterThan(String value) {
            addCriterion("ODSBDATE >", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateGreaterThanOrEqualTo(String value) {
            addCriterion("ODSBDATE >=", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateLessThan(String value) {
            addCriterion("ODSBDATE <", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateLessThanOrEqualTo(String value) {
            addCriterion("ODSBDATE <=", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateLike(String value) {
            addCriterion("ODSBDATE like", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotLike(String value) {
            addCriterion("ODSBDATE not like", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateIn(List<String> values) {
            addCriterion("ODSBDATE in", values, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotIn(List<String> values) {
            addCriterion("ODSBDATE not in", values, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateBetween(String value1, String value2) {
            addCriterion("ODSBDATE between", value1, value2, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotBetween(String value1, String value2) {
            addCriterion("ODSBDATE not between", value1, value2, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeIsNull() {
            addCriterion("ODSBTIME is null");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeIsNotNull() {
            addCriterion("ODSBTIME is not null");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeEqualTo(String value) {
            addCriterion("ODSBTIME =", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotEqualTo(String value) {
            addCriterion("ODSBTIME <>", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeGreaterThan(String value) {
            addCriterion("ODSBTIME >", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ODSBTIME >=", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeLessThan(String value) {
            addCriterion("ODSBTIME <", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeLessThanOrEqualTo(String value) {
            addCriterion("ODSBTIME <=", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeLike(String value) {
            addCriterion("ODSBTIME like", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotLike(String value) {
            addCriterion("ODSBTIME not like", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeIn(List<String> values) {
            addCriterion("ODSBTIME in", values, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotIn(List<String> values) {
            addCriterion("ODSBTIME not in", values, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeBetween(String value1, String value2) {
            addCriterion("ODSBTIME between", value1, value2, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotBetween(String value1, String value2) {
            addCriterion("ODSBTIME not between", value1, value2, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Long value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Long value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Long value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Long value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Long value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Long value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Long> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Long> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Long value1, Long value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Long value1, Long value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("AREACODE is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("AREACODE is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("AREACODE =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("AREACODE <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("AREACODE >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("AREACODE >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("AREACODE <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("AREACODE <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("AREACODE like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("AREACODE not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("AREACODE in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("AREACODE not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("AREACODE between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("AREACODE not between", value1, value2, "areacode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_CARDBASEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}