package org.fbi.gwk.repository.model.gwk;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LsConsumeinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public LsConsumeinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLshIsNull() {
            addCriterion("LSH is null");
            return (Criteria) this;
        }

        public Criteria andLshIsNotNull() {
            addCriterion("LSH is not null");
            return (Criteria) this;
        }

        public Criteria andLshEqualTo(String value) {
            addCriterion("LSH =", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotEqualTo(String value) {
            addCriterion("LSH <>", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshGreaterThan(String value) {
            addCriterion("LSH >", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshGreaterThanOrEqualTo(String value) {
            addCriterion("LSH >=", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshLessThan(String value) {
            addCriterion("LSH <", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshLessThanOrEqualTo(String value) {
            addCriterion("LSH <=", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshLike(String value) {
            addCriterion("LSH like", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotLike(String value) {
            addCriterion("LSH not like", value, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshIn(List<String> values) {
            addCriterion("LSH in", values, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotIn(List<String> values) {
            addCriterion("LSH not in", values, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshBetween(String value1, String value2) {
            addCriterion("LSH between", value1, value2, "lsh");
            return (Criteria) this;
        }

        public Criteria andLshNotBetween(String value1, String value2) {
            addCriterion("LSH not between", value1, value2, "lsh");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("ACCOUNT =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("ACCOUNT <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("ACCOUNT >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("ACCOUNT <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("ACCOUNT like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("ACCOUNT not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("ACCOUNT in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("ACCOUNT not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("ACCOUNT between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andBusidateIsNull() {
            addCriterion("BUSIDATE is null");
            return (Criteria) this;
        }

        public Criteria andBusidateIsNotNull() {
            addCriterion("BUSIDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBusidateEqualTo(String value) {
            addCriterion("BUSIDATE =", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateNotEqualTo(String value) {
            addCriterion("BUSIDATE <>", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateGreaterThan(String value) {
            addCriterion("BUSIDATE >", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateGreaterThanOrEqualTo(String value) {
            addCriterion("BUSIDATE >=", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateLessThan(String value) {
            addCriterion("BUSIDATE <", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateLessThanOrEqualTo(String value) {
            addCriterion("BUSIDATE <=", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateLike(String value) {
            addCriterion("BUSIDATE like", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateNotLike(String value) {
            addCriterion("BUSIDATE not like", value, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateIn(List<String> values) {
            addCriterion("BUSIDATE in", values, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateNotIn(List<String> values) {
            addCriterion("BUSIDATE not in", values, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateBetween(String value1, String value2) {
            addCriterion("BUSIDATE between", value1, value2, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusidateNotBetween(String value1, String value2) {
            addCriterion("BUSIDATE not between", value1, value2, "busidate");
            return (Criteria) this;
        }

        public Criteria andBusimoneyIsNull() {
            addCriterion("BUSIMONEY is null");
            return (Criteria) this;
        }

        public Criteria andBusimoneyIsNotNull() {
            addCriterion("BUSIMONEY is not null");
            return (Criteria) this;
        }

        public Criteria andBusimoneyEqualTo(BigDecimal value) {
            addCriterion("BUSIMONEY =", value, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyNotEqualTo(BigDecimal value) {
            addCriterion("BUSIMONEY <>", value, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyGreaterThan(BigDecimal value) {
            addCriterion("BUSIMONEY >", value, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BUSIMONEY >=", value, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyLessThan(BigDecimal value) {
            addCriterion("BUSIMONEY <", value, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BUSIMONEY <=", value, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyIn(List<BigDecimal> values) {
            addCriterion("BUSIMONEY in", values, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyNotIn(List<BigDecimal> values) {
            addCriterion("BUSIMONEY not in", values, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUSIMONEY between", value1, value2, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusimoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUSIMONEY not between", value1, value2, "busimoney");
            return (Criteria) this;
        }

        public Criteria andBusinameIsNull() {
            addCriterion("BUSINAME is null");
            return (Criteria) this;
        }

        public Criteria andBusinameIsNotNull() {
            addCriterion("BUSINAME is not null");
            return (Criteria) this;
        }

        public Criteria andBusinameEqualTo(String value) {
            addCriterion("BUSINAME =", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameNotEqualTo(String value) {
            addCriterion("BUSINAME <>", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameGreaterThan(String value) {
            addCriterion("BUSINAME >", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINAME >=", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameLessThan(String value) {
            addCriterion("BUSINAME <", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameLessThanOrEqualTo(String value) {
            addCriterion("BUSINAME <=", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameLike(String value) {
            addCriterion("BUSINAME like", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameNotLike(String value) {
            addCriterion("BUSINAME not like", value, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameIn(List<String> values) {
            addCriterion("BUSINAME in", values, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameNotIn(List<String> values) {
            addCriterion("BUSINAME not in", values, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameBetween(String value1, String value2) {
            addCriterion("BUSINAME between", value1, value2, "businame");
            return (Criteria) this;
        }

        public Criteria andBusinameNotBetween(String value1, String value2) {
            addCriterion("BUSINAME not between", value1, value2, "businame");
            return (Criteria) this;
        }

        public Criteria andCardnameIsNull() {
            addCriterion("CARDNAME is null");
            return (Criteria) this;
        }

        public Criteria andCardnameIsNotNull() {
            addCriterion("CARDNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCardnameEqualTo(String value) {
            addCriterion("CARDNAME =", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotEqualTo(String value) {
            addCriterion("CARDNAME <>", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameGreaterThan(String value) {
            addCriterion("CARDNAME >", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameGreaterThanOrEqualTo(String value) {
            addCriterion("CARDNAME >=", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLessThan(String value) {
            addCriterion("CARDNAME <", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLessThanOrEqualTo(String value) {
            addCriterion("CARDNAME <=", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLike(String value) {
            addCriterion("CARDNAME like", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotLike(String value) {
            addCriterion("CARDNAME not like", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameIn(List<String> values) {
            addCriterion("CARDNAME in", values, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotIn(List<String> values) {
            addCriterion("CARDNAME not in", values, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameBetween(String value1, String value2) {
            addCriterion("CARDNAME between", value1, value2, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotBetween(String value1, String value2) {
            addCriterion("CARDNAME not between", value1, value2, "cardname");
            return (Criteria) this;
        }

        public Criteria andLimitdateIsNull() {
            addCriterion("LIMITDATE is null");
            return (Criteria) this;
        }

        public Criteria andLimitdateIsNotNull() {
            addCriterion("LIMITDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLimitdateEqualTo(String value) {
            addCriterion("LIMITDATE =", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateNotEqualTo(String value) {
            addCriterion("LIMITDATE <>", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateGreaterThan(String value) {
            addCriterion("LIMITDATE >", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateGreaterThanOrEqualTo(String value) {
            addCriterion("LIMITDATE >=", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateLessThan(String value) {
            addCriterion("LIMITDATE <", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateLessThanOrEqualTo(String value) {
            addCriterion("LIMITDATE <=", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateLike(String value) {
            addCriterion("LIMITDATE like", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateNotLike(String value) {
            addCriterion("LIMITDATE not like", value, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateIn(List<String> values) {
            addCriterion("LIMITDATE in", values, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateNotIn(List<String> values) {
            addCriterion("LIMITDATE not in", values, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateBetween(String value1, String value2) {
            addCriterion("LIMITDATE between", value1, value2, "limitdate");
            return (Criteria) this;
        }

        public Criteria andLimitdateNotBetween(String value1, String value2) {
            addCriterion("LIMITDATE not between", value1, value2, "limitdate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(Date value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(Date value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(Date value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(Date value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(Date value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<Date> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<Date> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(Date value1, Date value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(Date value1, Date value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTxCdIsNull() {
            addCriterion("TX_CD is null");
            return (Criteria) this;
        }

        public Criteria andTxCdIsNotNull() {
            addCriterion("TX_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTxCdEqualTo(String value) {
            addCriterion("TX_CD =", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotEqualTo(String value) {
            addCriterion("TX_CD <>", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdGreaterThan(String value) {
            addCriterion("TX_CD >", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdGreaterThanOrEqualTo(String value) {
            addCriterion("TX_CD >=", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdLessThan(String value) {
            addCriterion("TX_CD <", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdLessThanOrEqualTo(String value) {
            addCriterion("TX_CD <=", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdLike(String value) {
            addCriterion("TX_CD like", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotLike(String value) {
            addCriterion("TX_CD not like", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdIn(List<String> values) {
            addCriterion("TX_CD in", values, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotIn(List<String> values) {
            addCriterion("TX_CD not in", values, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdBetween(String value1, String value2) {
            addCriterion("TX_CD between", value1, value2, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotBetween(String value1, String value2) {
            addCriterion("TX_CD not between", value1, value2, "txCd");
            return (Criteria) this;
        }

        public Criteria andRefNumberIsNull() {
            addCriterion("REF_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andRefNumberIsNotNull() {
            addCriterion("REF_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andRefNumberEqualTo(String value) {
            addCriterion("REF_NUMBER =", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberNotEqualTo(String value) {
            addCriterion("REF_NUMBER <>", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberGreaterThan(String value) {
            addCriterion("REF_NUMBER >", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberGreaterThanOrEqualTo(String value) {
            addCriterion("REF_NUMBER >=", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberLessThan(String value) {
            addCriterion("REF_NUMBER <", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberLessThanOrEqualTo(String value) {
            addCriterion("REF_NUMBER <=", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberLike(String value) {
            addCriterion("REF_NUMBER like", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberNotLike(String value) {
            addCriterion("REF_NUMBER not like", value, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberIn(List<String> values) {
            addCriterion("REF_NUMBER in", values, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberNotIn(List<String> values) {
            addCriterion("REF_NUMBER not in", values, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberBetween(String value1, String value2) {
            addCriterion("REF_NUMBER between", value1, value2, "refNumber");
            return (Criteria) this;
        }

        public Criteria andRefNumberNotBetween(String value1, String value2) {
            addCriterion("REF_NUMBER not between", value1, value2, "refNumber");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoIsNull() {
            addCriterion("CMBI_MERCH_NO is null");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoIsNotNull() {
            addCriterion("CMBI_MERCH_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO =", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO <>", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoGreaterThan(String value) {
            addCriterion("CMBI_MERCH_NO >", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoGreaterThanOrEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO >=", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoLessThan(String value) {
            addCriterion("CMBI_MERCH_NO <", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoLessThanOrEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO <=", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoLike(String value) {
            addCriterion("CMBI_MERCH_NO like", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotLike(String value) {
            addCriterion("CMBI_MERCH_NO not like", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoIn(List<String> values) {
            addCriterion("CMBI_MERCH_NO in", values, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotIn(List<String> values) {
            addCriterion("CMBI_MERCH_NO not in", values, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoBetween(String value1, String value2) {
            addCriterion("CMBI_MERCH_NO between", value1, value2, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotBetween(String value1, String value2) {
            addCriterion("CMBI_MERCH_NO not between", value1, value2, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andInacDateIsNull() {
            addCriterion("INAC_DATE is null");
            return (Criteria) this;
        }

        public Criteria andInacDateIsNotNull() {
            addCriterion("INAC_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andInacDateEqualTo(String value) {
            addCriterion("INAC_DATE =", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotEqualTo(String value) {
            addCriterion("INAC_DATE <>", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateGreaterThan(String value) {
            addCriterion("INAC_DATE >", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateGreaterThanOrEqualTo(String value) {
            addCriterion("INAC_DATE >=", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateLessThan(String value) {
            addCriterion("INAC_DATE <", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateLessThanOrEqualTo(String value) {
            addCriterion("INAC_DATE <=", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateLike(String value) {
            addCriterion("INAC_DATE like", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotLike(String value) {
            addCriterion("INAC_DATE not like", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateIn(List<String> values) {
            addCriterion("INAC_DATE in", values, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotIn(List<String> values) {
            addCriterion("INAC_DATE not in", values, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateBetween(String value1, String value2) {
            addCriterion("INAC_DATE between", value1, value2, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotBetween(String value1, String value2) {
            addCriterion("INAC_DATE not between", value1, value2, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacAmtIsNull() {
            addCriterion("INAC_AMT is null");
            return (Criteria) this;
        }

        public Criteria andInacAmtIsNotNull() {
            addCriterion("INAC_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andInacAmtEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT =", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtNotEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT <>", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtGreaterThan(BigDecimal value) {
            addCriterion("INAC_AMT >", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT >=", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtLessThan(BigDecimal value) {
            addCriterion("INAC_AMT <", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT <=", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtIn(List<BigDecimal> values) {
            addCriterion("INAC_AMT in", values, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtNotIn(List<BigDecimal> values) {
            addCriterion("INAC_AMT not in", values, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAC_AMT between", value1, value2, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAC_AMT not between", value1, value2, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andTxlogIsNull() {
            addCriterion("TXLOG is null");
            return (Criteria) this;
        }

        public Criteria andTxlogIsNotNull() {
            addCriterion("TXLOG is not null");
            return (Criteria) this;
        }

        public Criteria andTxlogEqualTo(String value) {
            addCriterion("TXLOG =", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotEqualTo(String value) {
            addCriterion("TXLOG <>", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogGreaterThan(String value) {
            addCriterion("TXLOG >", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogGreaterThanOrEqualTo(String value) {
            addCriterion("TXLOG >=", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogLessThan(String value) {
            addCriterion("TXLOG <", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogLessThanOrEqualTo(String value) {
            addCriterion("TXLOG <=", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogLike(String value) {
            addCriterion("TXLOG like", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotLike(String value) {
            addCriterion("TXLOG not like", value, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogIn(List<String> values) {
            addCriterion("TXLOG in", values, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotIn(List<String> values) {
            addCriterion("TXLOG not in", values, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogBetween(String value1, String value2) {
            addCriterion("TXLOG between", value1, value2, "txlog");
            return (Criteria) this;
        }

        public Criteria andTxlogNotBetween(String value1, String value2) {
            addCriterion("TXLOG not between", value1, value2, "txlog");
            return (Criteria) this;
        }

        public Criteria andOdsbdateIsNull() {
            addCriterion("ODSBDATE is null");
            return (Criteria) this;
        }

        public Criteria andOdsbdateIsNotNull() {
            addCriterion("ODSBDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOdsbdateEqualTo(String value) {
            addCriterion("ODSBDATE =", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotEqualTo(String value) {
            addCriterion("ODSBDATE <>", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateGreaterThan(String value) {
            addCriterion("ODSBDATE >", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateGreaterThanOrEqualTo(String value) {
            addCriterion("ODSBDATE >=", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateLessThan(String value) {
            addCriterion("ODSBDATE <", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateLessThanOrEqualTo(String value) {
            addCriterion("ODSBDATE <=", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateLike(String value) {
            addCriterion("ODSBDATE like", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotLike(String value) {
            addCriterion("ODSBDATE not like", value, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateIn(List<String> values) {
            addCriterion("ODSBDATE in", values, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotIn(List<String> values) {
            addCriterion("ODSBDATE not in", values, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateBetween(String value1, String value2) {
            addCriterion("ODSBDATE between", value1, value2, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbdateNotBetween(String value1, String value2) {
            addCriterion("ODSBDATE not between", value1, value2, "odsbdate");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeIsNull() {
            addCriterion("ODSBTIME is null");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeIsNotNull() {
            addCriterion("ODSBTIME is not null");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeEqualTo(String value) {
            addCriterion("ODSBTIME =", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotEqualTo(String value) {
            addCriterion("ODSBTIME <>", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeGreaterThan(String value) {
            addCriterion("ODSBTIME >", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ODSBTIME >=", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeLessThan(String value) {
            addCriterion("ODSBTIME <", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeLessThanOrEqualTo(String value) {
            addCriterion("ODSBTIME <=", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeLike(String value) {
            addCriterion("ODSBTIME like", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotLike(String value) {
            addCriterion("ODSBTIME not like", value, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeIn(List<String> values) {
            addCriterion("ODSBTIME in", values, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotIn(List<String> values) {
            addCriterion("ODSBTIME not in", values, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeBetween(String value1, String value2) {
            addCriterion("ODSBTIME between", value1, value2, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andOdsbtimeNotBetween(String value1, String value2) {
            addCriterion("ODSBTIME not between", value1, value2, "odsbtime");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Long value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Long value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Long value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Long value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Long value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Long value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Long> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Long> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Long value1, Long value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Long value1, Long value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRefDateIsNull() {
            addCriterion("REF_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRefDateIsNotNull() {
            addCriterion("REF_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRefDateEqualTo(String value) {
            addCriterion("REF_DATE =", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotEqualTo(String value) {
            addCriterion("REF_DATE <>", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateGreaterThan(String value) {
            addCriterion("REF_DATE >", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateGreaterThanOrEqualTo(String value) {
            addCriterion("REF_DATE >=", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateLessThan(String value) {
            addCriterion("REF_DATE <", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateLessThanOrEqualTo(String value) {
            addCriterion("REF_DATE <=", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateLike(String value) {
            addCriterion("REF_DATE like", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotLike(String value) {
            addCriterion("REF_DATE not like", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateIn(List<String> values) {
            addCriterion("REF_DATE in", values, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotIn(List<String> values) {
            addCriterion("REF_DATE not in", values, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateBetween(String value1, String value2) {
            addCriterion("REF_DATE between", value1, value2, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotBetween(String value1, String value2) {
            addCriterion("REF_DATE not between", value1, value2, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdIsNull() {
            addCriterion("REF_BATCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdIsNotNull() {
            addCriterion("REF_BATCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdEqualTo(String value) {
            addCriterion("REF_BATCH_ID =", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotEqualTo(String value) {
            addCriterion("REF_BATCH_ID <>", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdGreaterThan(String value) {
            addCriterion("REF_BATCH_ID >", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("REF_BATCH_ID >=", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdLessThan(String value) {
            addCriterion("REF_BATCH_ID <", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdLessThanOrEqualTo(String value) {
            addCriterion("REF_BATCH_ID <=", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdLike(String value) {
            addCriterion("REF_BATCH_ID like", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotLike(String value) {
            addCriterion("REF_BATCH_ID not like", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdIn(List<String> values) {
            addCriterion("REF_BATCH_ID in", values, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotIn(List<String> values) {
            addCriterion("REF_BATCH_ID not in", values, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdBetween(String value1, String value2) {
            addCriterion("REF_BATCH_ID between", value1, value2, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotBetween(String value1, String value2) {
            addCriterion("REF_BATCH_ID not between", value1, value2, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoIsNull() {
            addCriterion("REF_SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoIsNotNull() {
            addCriterion("REF_SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoEqualTo(String value) {
            addCriterion("REF_SEQ_NO =", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotEqualTo(String value) {
            addCriterion("REF_SEQ_NO <>", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoGreaterThan(String value) {
            addCriterion("REF_SEQ_NO >", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoGreaterThanOrEqualTo(String value) {
            addCriterion("REF_SEQ_NO >=", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoLessThan(String value) {
            addCriterion("REF_SEQ_NO <", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoLessThanOrEqualTo(String value) {
            addCriterion("REF_SEQ_NO <=", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoLike(String value) {
            addCriterion("REF_SEQ_NO like", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotLike(String value) {
            addCriterion("REF_SEQ_NO not like", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoIn(List<String> values) {
            addCriterion("REF_SEQ_NO in", values, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotIn(List<String> values) {
            addCriterion("REF_SEQ_NO not in", values, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoBetween(String value1, String value2) {
            addCriterion("REF_SEQ_NO between", value1, value2, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotBetween(String value1, String value2) {
            addCriterion("REF_SEQ_NO not between", value1, value2, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("AREACODE is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("AREACODE is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("AREACODE =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("AREACODE <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("AREACODE >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("AREACODE >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("AREACODE <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("AREACODE <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("AREACODE like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("AREACODE not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("AREACODE in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("AREACODE not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("AREACODE between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("AREACODE not between", value1, value2, "areacode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_CONSUMEINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}