package org.fbi.gwk.repository.model.gwk;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LsPersonalinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public LsPersonalinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecinsequenceIsNull() {
            addCriterion("RECINSEQUENCE is null");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceIsNotNull() {
            addCriterion("RECINSEQUENCE is not null");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceEqualTo(String value) {
            addCriterion("RECINSEQUENCE =", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceNotEqualTo(String value) {
            addCriterion("RECINSEQUENCE <>", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceGreaterThan(String value) {
            addCriterion("RECINSEQUENCE >", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceGreaterThanOrEqualTo(String value) {
            addCriterion("RECINSEQUENCE >=", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceLessThan(String value) {
            addCriterion("RECINSEQUENCE <", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceLessThanOrEqualTo(String value) {
            addCriterion("RECINSEQUENCE <=", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceLike(String value) {
            addCriterion("RECINSEQUENCE like", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceNotLike(String value) {
            addCriterion("RECINSEQUENCE not like", value, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceIn(List<String> values) {
            addCriterion("RECINSEQUENCE in", values, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceNotIn(List<String> values) {
            addCriterion("RECINSEQUENCE not in", values, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceBetween(String value1, String value2) {
            addCriterion("RECINSEQUENCE between", value1, value2, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andRecinsequenceNotBetween(String value1, String value2) {
            addCriterion("RECINSEQUENCE not between", value1, value2, "recinsequence");
            return (Criteria) this;
        }

        public Criteria andPernameIsNull() {
            addCriterion("PERNAME is null");
            return (Criteria) this;
        }

        public Criteria andPernameIsNotNull() {
            addCriterion("PERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPernameEqualTo(String value) {
            addCriterion("PERNAME =", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameNotEqualTo(String value) {
            addCriterion("PERNAME <>", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameGreaterThan(String value) {
            addCriterion("PERNAME >", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameGreaterThanOrEqualTo(String value) {
            addCriterion("PERNAME >=", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameLessThan(String value) {
            addCriterion("PERNAME <", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameLessThanOrEqualTo(String value) {
            addCriterion("PERNAME <=", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameLike(String value) {
            addCriterion("PERNAME like", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameNotLike(String value) {
            addCriterion("PERNAME not like", value, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameIn(List<String> values) {
            addCriterion("PERNAME in", values, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameNotIn(List<String> values) {
            addCriterion("PERNAME not in", values, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameBetween(String value1, String value2) {
            addCriterion("PERNAME between", value1, value2, "pername");
            return (Criteria) this;
        }

        public Criteria andPernameNotBetween(String value1, String value2) {
            addCriterion("PERNAME not between", value1, value2, "pername");
            return (Criteria) this;
        }

        public Criteria andPeridIsNull() {
            addCriterion("PERID is null");
            return (Criteria) this;
        }

        public Criteria andPeridIsNotNull() {
            addCriterion("PERID is not null");
            return (Criteria) this;
        }

        public Criteria andPeridEqualTo(String value) {
            addCriterion("PERID =", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridNotEqualTo(String value) {
            addCriterion("PERID <>", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridGreaterThan(String value) {
            addCriterion("PERID >", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridGreaterThanOrEqualTo(String value) {
            addCriterion("PERID >=", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridLessThan(String value) {
            addCriterion("PERID <", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridLessThanOrEqualTo(String value) {
            addCriterion("PERID <=", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridLike(String value) {
            addCriterion("PERID like", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridNotLike(String value) {
            addCriterion("PERID not like", value, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridIn(List<String> values) {
            addCriterion("PERID in", values, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridNotIn(List<String> values) {
            addCriterion("PERID not in", values, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridBetween(String value1, String value2) {
            addCriterion("PERID between", value1, value2, "perid");
            return (Criteria) this;
        }

        public Criteria andPeridNotBetween(String value1, String value2) {
            addCriterion("PERID not between", value1, value2, "perid");
            return (Criteria) this;
        }

        public Criteria andDeptcodeIsNull() {
            addCriterion("DEPTCODE is null");
            return (Criteria) this;
        }

        public Criteria andDeptcodeIsNotNull() {
            addCriterion("DEPTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andDeptcodeEqualTo(String value) {
            addCriterion("DEPTCODE =", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeNotEqualTo(String value) {
            addCriterion("DEPTCODE <>", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeGreaterThan(String value) {
            addCriterion("DEPTCODE >", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTCODE >=", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeLessThan(String value) {
            addCriterion("DEPTCODE <", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeLessThanOrEqualTo(String value) {
            addCriterion("DEPTCODE <=", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeLike(String value) {
            addCriterion("DEPTCODE like", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeNotLike(String value) {
            addCriterion("DEPTCODE not like", value, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeIn(List<String> values) {
            addCriterion("DEPTCODE in", values, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeNotIn(List<String> values) {
            addCriterion("DEPTCODE not in", values, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeBetween(String value1, String value2) {
            addCriterion("DEPTCODE between", value1, value2, "deptcode");
            return (Criteria) this;
        }

        public Criteria andDeptcodeNotBetween(String value1, String value2) {
            addCriterion("DEPTCODE not between", value1, value2, "deptcode");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(BigDecimal value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(BigDecimal value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(BigDecimal value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(BigDecimal value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<BigDecimal> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<BigDecimal> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andCreatecodeIsNull() {
            addCriterion("CREATECODE is null");
            return (Criteria) this;
        }

        public Criteria andCreatecodeIsNotNull() {
            addCriterion("CREATECODE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatecodeEqualTo(BigDecimal value) {
            addCriterion("CREATECODE =", value, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeNotEqualTo(BigDecimal value) {
            addCriterion("CREATECODE <>", value, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeGreaterThan(BigDecimal value) {
            addCriterion("CREATECODE >", value, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATECODE >=", value, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeLessThan(BigDecimal value) {
            addCriterion("CREATECODE <", value, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATECODE <=", value, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeIn(List<BigDecimal> values) {
            addCriterion("CREATECODE in", values, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeNotIn(List<BigDecimal> values) {
            addCriterion("CREATECODE not in", values, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATECODE between", value1, value2, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatecodeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATECODE not between", value1, value2, "createcode");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeIsNull() {
            addCriterion("SUPERDEPTCODE is null");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeIsNotNull() {
            addCriterion("SUPERDEPTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeEqualTo(String value) {
            addCriterion("SUPERDEPTCODE =", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeNotEqualTo(String value) {
            addCriterion("SUPERDEPTCODE <>", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeGreaterThan(String value) {
            addCriterion("SUPERDEPTCODE >", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeGreaterThanOrEqualTo(String value) {
            addCriterion("SUPERDEPTCODE >=", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeLessThan(String value) {
            addCriterion("SUPERDEPTCODE <", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeLessThanOrEqualTo(String value) {
            addCriterion("SUPERDEPTCODE <=", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeLike(String value) {
            addCriterion("SUPERDEPTCODE like", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeNotLike(String value) {
            addCriterion("SUPERDEPTCODE not like", value, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeIn(List<String> values) {
            addCriterion("SUPERDEPTCODE in", values, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeNotIn(List<String> values) {
            addCriterion("SUPERDEPTCODE not in", values, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeBetween(String value1, String value2) {
            addCriterion("SUPERDEPTCODE between", value1, value2, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andSuperdeptcodeNotBetween(String value1, String value2) {
            addCriterion("SUPERDEPTCODE not between", value1, value2, "superdeptcode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("AREACODE is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("AREACODE is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("AREACODE =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("AREACODE <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("AREACODE >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("AREACODE >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("AREACODE <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("AREACODE <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("AREACODE like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("AREACODE not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("AREACODE in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("AREACODE not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("AREACODE between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("AREACODE not between", value1, value2, "areacode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}