package org.fbi.gwk.repository.model.gwk;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OdsbCrdCrtTradExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public OdsbCrdCrtTradExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActpIsNull() {
            addCriterion("ACTP is null");
            return (Criteria) this;
        }

        public Criteria andActpIsNotNull() {
            addCriterion("ACTP is not null");
            return (Criteria) this;
        }

        public Criteria andActpEqualTo(String value) {
            addCriterion("ACTP =", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpNotEqualTo(String value) {
            addCriterion("ACTP <>", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpGreaterThan(String value) {
            addCriterion("ACTP >", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpGreaterThanOrEqualTo(String value) {
            addCriterion("ACTP >=", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpLessThan(String value) {
            addCriterion("ACTP <", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpLessThanOrEqualTo(String value) {
            addCriterion("ACTP <=", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpLike(String value) {
            addCriterion("ACTP like", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpNotLike(String value) {
            addCriterion("ACTP not like", value, "actp");
            return (Criteria) this;
        }

        public Criteria andActpIn(List<String> values) {
            addCriterion("ACTP in", values, "actp");
            return (Criteria) this;
        }

        public Criteria andActpNotIn(List<String> values) {
            addCriterion("ACTP not in", values, "actp");
            return (Criteria) this;
        }

        public Criteria andActpBetween(String value1, String value2) {
            addCriterion("ACTP between", value1, value2, "actp");
            return (Criteria) this;
        }

        public Criteria andActpNotBetween(String value1, String value2) {
            addCriterion("ACTP not between", value1, value2, "actp");
            return (Criteria) this;
        }

        public Criteria andCrdTypIsNull() {
            addCriterion("CRD_TYP is null");
            return (Criteria) this;
        }

        public Criteria andCrdTypIsNotNull() {
            addCriterion("CRD_TYP is not null");
            return (Criteria) this;
        }

        public Criteria andCrdTypEqualTo(String value) {
            addCriterion("CRD_TYP =", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypNotEqualTo(String value) {
            addCriterion("CRD_TYP <>", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypGreaterThan(String value) {
            addCriterion("CRD_TYP >", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypGreaterThanOrEqualTo(String value) {
            addCriterion("CRD_TYP >=", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypLessThan(String value) {
            addCriterion("CRD_TYP <", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypLessThanOrEqualTo(String value) {
            addCriterion("CRD_TYP <=", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypLike(String value) {
            addCriterion("CRD_TYP like", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypNotLike(String value) {
            addCriterion("CRD_TYP not like", value, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypIn(List<String> values) {
            addCriterion("CRD_TYP in", values, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypNotIn(List<String> values) {
            addCriterion("CRD_TYP not in", values, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypBetween(String value1, String value2) {
            addCriterion("CRD_TYP between", value1, value2, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdTypNotBetween(String value1, String value2) {
            addCriterion("CRD_TYP not between", value1, value2, "crdTyp");
            return (Criteria) this;
        }

        public Criteria andCrdNoIsNull() {
            addCriterion("CRD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCrdNoIsNotNull() {
            addCriterion("CRD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCrdNoEqualTo(String value) {
            addCriterion("CRD_NO =", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoNotEqualTo(String value) {
            addCriterion("CRD_NO <>", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoGreaterThan(String value) {
            addCriterion("CRD_NO >", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoGreaterThanOrEqualTo(String value) {
            addCriterion("CRD_NO >=", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoLessThan(String value) {
            addCriterion("CRD_NO <", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoLessThanOrEqualTo(String value) {
            addCriterion("CRD_NO <=", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoLike(String value) {
            addCriterion("CRD_NO like", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoNotLike(String value) {
            addCriterion("CRD_NO not like", value, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoIn(List<String> values) {
            addCriterion("CRD_NO in", values, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoNotIn(List<String> values) {
            addCriterion("CRD_NO not in", values, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoBetween(String value1, String value2) {
            addCriterion("CRD_NO between", value1, value2, "crdNo");
            return (Criteria) this;
        }

        public Criteria andCrdNoNotBetween(String value1, String value2) {
            addCriterion("CRD_NO not between", value1, value2, "crdNo");
            return (Criteria) this;
        }

        public Criteria andTxDayIsNull() {
            addCriterion("TX_DAY is null");
            return (Criteria) this;
        }

        public Criteria andTxDayIsNotNull() {
            addCriterion("TX_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andTxDayEqualTo(String value) {
            addCriterion("TX_DAY =", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayNotEqualTo(String value) {
            addCriterion("TX_DAY <>", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayGreaterThan(String value) {
            addCriterion("TX_DAY >", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayGreaterThanOrEqualTo(String value) {
            addCriterion("TX_DAY >=", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayLessThan(String value) {
            addCriterion("TX_DAY <", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayLessThanOrEqualTo(String value) {
            addCriterion("TX_DAY <=", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayLike(String value) {
            addCriterion("TX_DAY like", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayNotLike(String value) {
            addCriterion("TX_DAY not like", value, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayIn(List<String> values) {
            addCriterion("TX_DAY in", values, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayNotIn(List<String> values) {
            addCriterion("TX_DAY not in", values, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayBetween(String value1, String value2) {
            addCriterion("TX_DAY between", value1, value2, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxDayNotBetween(String value1, String value2) {
            addCriterion("TX_DAY not between", value1, value2, "txDay");
            return (Criteria) this;
        }

        public Criteria andTxCdIsNull() {
            addCriterion("TX_CD is null");
            return (Criteria) this;
        }

        public Criteria andTxCdIsNotNull() {
            addCriterion("TX_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTxCdEqualTo(String value) {
            addCriterion("TX_CD =", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotEqualTo(String value) {
            addCriterion("TX_CD <>", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdGreaterThan(String value) {
            addCriterion("TX_CD >", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdGreaterThanOrEqualTo(String value) {
            addCriterion("TX_CD >=", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdLessThan(String value) {
            addCriterion("TX_CD <", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdLessThanOrEqualTo(String value) {
            addCriterion("TX_CD <=", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdLike(String value) {
            addCriterion("TX_CD like", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotLike(String value) {
            addCriterion("TX_CD not like", value, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdIn(List<String> values) {
            addCriterion("TX_CD in", values, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotIn(List<String> values) {
            addCriterion("TX_CD not in", values, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdBetween(String value1, String value2) {
            addCriterion("TX_CD between", value1, value2, "txCd");
            return (Criteria) this;
        }

        public Criteria andTxCdNotBetween(String value1, String value2) {
            addCriterion("TX_CD not between", value1, value2, "txCd");
            return (Criteria) this;
        }

        public Criteria andInacAmtIsNull() {
            addCriterion("INAC_AMT is null");
            return (Criteria) this;
        }

        public Criteria andInacAmtIsNotNull() {
            addCriterion("INAC_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andInacAmtEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT =", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtNotEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT <>", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtGreaterThan(BigDecimal value) {
            addCriterion("INAC_AMT >", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT >=", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtLessThan(BigDecimal value) {
            addCriterion("INAC_AMT <", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INAC_AMT <=", value, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtIn(List<BigDecimal> values) {
            addCriterion("INAC_AMT in", values, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtNotIn(List<BigDecimal> values) {
            addCriterion("INAC_AMT not in", values, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAC_AMT between", value1, value2, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAC_AMT not between", value1, value2, "inacAmt");
            return (Criteria) this;
        }

        public Criteria andInacDateIsNull() {
            addCriterion("INAC_DATE is null");
            return (Criteria) this;
        }

        public Criteria andInacDateIsNotNull() {
            addCriterion("INAC_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andInacDateEqualTo(String value) {
            addCriterion("INAC_DATE =", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotEqualTo(String value) {
            addCriterion("INAC_DATE <>", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateGreaterThan(String value) {
            addCriterion("INAC_DATE >", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateGreaterThanOrEqualTo(String value) {
            addCriterion("INAC_DATE >=", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateLessThan(String value) {
            addCriterion("INAC_DATE <", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateLessThanOrEqualTo(String value) {
            addCriterion("INAC_DATE <=", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateLike(String value) {
            addCriterion("INAC_DATE like", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotLike(String value) {
            addCriterion("INAC_DATE not like", value, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateIn(List<String> values) {
            addCriterion("INAC_DATE in", values, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotIn(List<String> values) {
            addCriterion("INAC_DATE not in", values, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateBetween(String value1, String value2) {
            addCriterion("INAC_DATE between", value1, value2, "inacDate");
            return (Criteria) this;
        }

        public Criteria andInacDateNotBetween(String value1, String value2) {
            addCriterion("INAC_DATE not between", value1, value2, "inacDate");
            return (Criteria) this;
        }

        public Criteria andSrcCdIsNull() {
            addCriterion("SRC_CD is null");
            return (Criteria) this;
        }

        public Criteria andSrcCdIsNotNull() {
            addCriterion("SRC_CD is not null");
            return (Criteria) this;
        }

        public Criteria andSrcCdEqualTo(String value) {
            addCriterion("SRC_CD =", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdNotEqualTo(String value) {
            addCriterion("SRC_CD <>", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdGreaterThan(String value) {
            addCriterion("SRC_CD >", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_CD >=", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdLessThan(String value) {
            addCriterion("SRC_CD <", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdLessThanOrEqualTo(String value) {
            addCriterion("SRC_CD <=", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdLike(String value) {
            addCriterion("SRC_CD like", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdNotLike(String value) {
            addCriterion("SRC_CD not like", value, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdIn(List<String> values) {
            addCriterion("SRC_CD in", values, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdNotIn(List<String> values) {
            addCriterion("SRC_CD not in", values, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdBetween(String value1, String value2) {
            addCriterion("SRC_CD between", value1, value2, "srcCd");
            return (Criteria) this;
        }

        public Criteria andSrcCdNotBetween(String value1, String value2) {
            addCriterion("SRC_CD not between", value1, value2, "srcCd");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeIsNull() {
            addCriterion("DHI_AUTH_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeIsNotNull() {
            addCriterion("DHI_AUTH_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeEqualTo(String value) {
            addCriterion("DHI_AUTH_CODE =", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeNotEqualTo(String value) {
            addCriterion("DHI_AUTH_CODE <>", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeGreaterThan(String value) {
            addCriterion("DHI_AUTH_CODE >", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DHI_AUTH_CODE >=", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeLessThan(String value) {
            addCriterion("DHI_AUTH_CODE <", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeLessThanOrEqualTo(String value) {
            addCriterion("DHI_AUTH_CODE <=", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeLike(String value) {
            addCriterion("DHI_AUTH_CODE like", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeNotLike(String value) {
            addCriterion("DHI_AUTH_CODE not like", value, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeIn(List<String> values) {
            addCriterion("DHI_AUTH_CODE in", values, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeNotIn(List<String> values) {
            addCriterion("DHI_AUTH_CODE not in", values, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeBetween(String value1, String value2) {
            addCriterion("DHI_AUTH_CODE between", value1, value2, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andDhiAuthCodeNotBetween(String value1, String value2) {
            addCriterion("DHI_AUTH_CODE not between", value1, value2, "dhiAuthCode");
            return (Criteria) this;
        }

        public Criteria andRefDateIsNull() {
            addCriterion("REF_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRefDateIsNotNull() {
            addCriterion("REF_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRefDateEqualTo(String value) {
            addCriterion("REF_DATE =", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotEqualTo(String value) {
            addCriterion("REF_DATE <>", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateGreaterThan(String value) {
            addCriterion("REF_DATE >", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateGreaterThanOrEqualTo(String value) {
            addCriterion("REF_DATE >=", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateLessThan(String value) {
            addCriterion("REF_DATE <", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateLessThanOrEqualTo(String value) {
            addCriterion("REF_DATE <=", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateLike(String value) {
            addCriterion("REF_DATE like", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotLike(String value) {
            addCriterion("REF_DATE not like", value, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateIn(List<String> values) {
            addCriterion("REF_DATE in", values, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotIn(List<String> values) {
            addCriterion("REF_DATE not in", values, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateBetween(String value1, String value2) {
            addCriterion("REF_DATE between", value1, value2, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefDateNotBetween(String value1, String value2) {
            addCriterion("REF_DATE not between", value1, value2, "refDate");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdIsNull() {
            addCriterion("REF_BATCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdIsNotNull() {
            addCriterion("REF_BATCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdEqualTo(String value) {
            addCriterion("REF_BATCH_ID =", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotEqualTo(String value) {
            addCriterion("REF_BATCH_ID <>", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdGreaterThan(String value) {
            addCriterion("REF_BATCH_ID >", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("REF_BATCH_ID >=", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdLessThan(String value) {
            addCriterion("REF_BATCH_ID <", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdLessThanOrEqualTo(String value) {
            addCriterion("REF_BATCH_ID <=", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdLike(String value) {
            addCriterion("REF_BATCH_ID like", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotLike(String value) {
            addCriterion("REF_BATCH_ID not like", value, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdIn(List<String> values) {
            addCriterion("REF_BATCH_ID in", values, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotIn(List<String> values) {
            addCriterion("REF_BATCH_ID not in", values, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdBetween(String value1, String value2) {
            addCriterion("REF_BATCH_ID between", value1, value2, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefBatchIdNotBetween(String value1, String value2) {
            addCriterion("REF_BATCH_ID not between", value1, value2, "refBatchId");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoIsNull() {
            addCriterion("REF_SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoIsNotNull() {
            addCriterion("REF_SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoEqualTo(String value) {
            addCriterion("REF_SEQ_NO =", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotEqualTo(String value) {
            addCriterion("REF_SEQ_NO <>", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoGreaterThan(String value) {
            addCriterion("REF_SEQ_NO >", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoGreaterThanOrEqualTo(String value) {
            addCriterion("REF_SEQ_NO >=", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoLessThan(String value) {
            addCriterion("REF_SEQ_NO <", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoLessThanOrEqualTo(String value) {
            addCriterion("REF_SEQ_NO <=", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoLike(String value) {
            addCriterion("REF_SEQ_NO like", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotLike(String value) {
            addCriterion("REF_SEQ_NO not like", value, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoIn(List<String> values) {
            addCriterion("REF_SEQ_NO in", values, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotIn(List<String> values) {
            addCriterion("REF_SEQ_NO not in", values, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoBetween(String value1, String value2) {
            addCriterion("REF_SEQ_NO between", value1, value2, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andRefSeqNoNotBetween(String value1, String value2) {
            addCriterion("REF_SEQ_NO not between", value1, value2, "refSeqNo");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgIsNull() {
            addCriterion("MERCHANT_ORG is null");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgIsNotNull() {
            addCriterion("MERCHANT_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgEqualTo(String value) {
            addCriterion("MERCHANT_ORG =", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgNotEqualTo(String value) {
            addCriterion("MERCHANT_ORG <>", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgGreaterThan(String value) {
            addCriterion("MERCHANT_ORG >", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ORG >=", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgLessThan(String value) {
            addCriterion("MERCHANT_ORG <", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ORG <=", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgLike(String value) {
            addCriterion("MERCHANT_ORG like", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgNotLike(String value) {
            addCriterion("MERCHANT_ORG not like", value, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgIn(List<String> values) {
            addCriterion("MERCHANT_ORG in", values, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgNotIn(List<String> values) {
            addCriterion("MERCHANT_ORG not in", values, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgBetween(String value1, String value2) {
            addCriterion("MERCHANT_ORG between", value1, value2, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andMerchantOrgNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ORG not between", value1, value2, "merchantOrg");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctIsNull() {
            addCriterion("DHI_MERCH_ACCT is null");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctIsNotNull() {
            addCriterion("DHI_MERCH_ACCT is not null");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctEqualTo(String value) {
            addCriterion("DHI_MERCH_ACCT =", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctNotEqualTo(String value) {
            addCriterion("DHI_MERCH_ACCT <>", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctGreaterThan(String value) {
            addCriterion("DHI_MERCH_ACCT >", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctGreaterThanOrEqualTo(String value) {
            addCriterion("DHI_MERCH_ACCT >=", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctLessThan(String value) {
            addCriterion("DHI_MERCH_ACCT <", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctLessThanOrEqualTo(String value) {
            addCriterion("DHI_MERCH_ACCT <=", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctLike(String value) {
            addCriterion("DHI_MERCH_ACCT like", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctNotLike(String value) {
            addCriterion("DHI_MERCH_ACCT not like", value, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctIn(List<String> values) {
            addCriterion("DHI_MERCH_ACCT in", values, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctNotIn(List<String> values) {
            addCriterion("DHI_MERCH_ACCT not in", values, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctBetween(String value1, String value2) {
            addCriterion("DHI_MERCH_ACCT between", value1, value2, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andDhiMerchAcctNotBetween(String value1, String value2) {
            addCriterion("DHI_MERCH_ACCT not between", value1, value2, "dhiMerchAcct");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoIsNull() {
            addCriterion("MERCHANT_KND_NO is null");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoIsNotNull() {
            addCriterion("MERCHANT_KND_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoEqualTo(String value) {
            addCriterion("MERCHANT_KND_NO =", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoNotEqualTo(String value) {
            addCriterion("MERCHANT_KND_NO <>", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoGreaterThan(String value) {
            addCriterion("MERCHANT_KND_NO >", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_KND_NO >=", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoLessThan(String value) {
            addCriterion("MERCHANT_KND_NO <", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_KND_NO <=", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoLike(String value) {
            addCriterion("MERCHANT_KND_NO like", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoNotLike(String value) {
            addCriterion("MERCHANT_KND_NO not like", value, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoIn(List<String> values) {
            addCriterion("MERCHANT_KND_NO in", values, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoNotIn(List<String> values) {
            addCriterion("MERCHANT_KND_NO not in", values, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoBetween(String value1, String value2) {
            addCriterion("MERCHANT_KND_NO between", value1, value2, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andMerchantKndNoNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_KND_NO not between", value1, value2, "merchantKndNo");
            return (Criteria) this;
        }

        public Criteria andFiller2IsNull() {
            addCriterion("FILLER_2 is null");
            return (Criteria) this;
        }

        public Criteria andFiller2IsNotNull() {
            addCriterion("FILLER_2 is not null");
            return (Criteria) this;
        }

        public Criteria andFiller2EqualTo(String value) {
            addCriterion("FILLER_2 =", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2NotEqualTo(String value) {
            addCriterion("FILLER_2 <>", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2GreaterThan(String value) {
            addCriterion("FILLER_2 >", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2GreaterThanOrEqualTo(String value) {
            addCriterion("FILLER_2 >=", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2LessThan(String value) {
            addCriterion("FILLER_2 <", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2LessThanOrEqualTo(String value) {
            addCriterion("FILLER_2 <=", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2Like(String value) {
            addCriterion("FILLER_2 like", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2NotLike(String value) {
            addCriterion("FILLER_2 not like", value, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2In(List<String> values) {
            addCriterion("FILLER_2 in", values, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2NotIn(List<String> values) {
            addCriterion("FILLER_2 not in", values, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2Between(String value1, String value2) {
            addCriterion("FILLER_2 between", value1, value2, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller2NotBetween(String value1, String value2) {
            addCriterion("FILLER_2 not between", value1, value2, "filler2");
            return (Criteria) this;
        }

        public Criteria andFiller3IsNull() {
            addCriterion("FILLER_3 is null");
            return (Criteria) this;
        }

        public Criteria andFiller3IsNotNull() {
            addCriterion("FILLER_3 is not null");
            return (Criteria) this;
        }

        public Criteria andFiller3EqualTo(String value) {
            addCriterion("FILLER_3 =", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3NotEqualTo(String value) {
            addCriterion("FILLER_3 <>", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3GreaterThan(String value) {
            addCriterion("FILLER_3 >", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3GreaterThanOrEqualTo(String value) {
            addCriterion("FILLER_3 >=", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3LessThan(String value) {
            addCriterion("FILLER_3 <", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3LessThanOrEqualTo(String value) {
            addCriterion("FILLER_3 <=", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3Like(String value) {
            addCriterion("FILLER_3 like", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3NotLike(String value) {
            addCriterion("FILLER_3 not like", value, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3In(List<String> values) {
            addCriterion("FILLER_3 in", values, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3NotIn(List<String> values) {
            addCriterion("FILLER_3 not in", values, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3Between(String value1, String value2) {
            addCriterion("FILLER_3 between", value1, value2, "filler3");
            return (Criteria) this;
        }

        public Criteria andFiller3NotBetween(String value1, String value2) {
            addCriterion("FILLER_3 not between", value1, value2, "filler3");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryIsNull() {
            addCriterion("TX_DSCRP_CNTRY is null");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryIsNotNull() {
            addCriterion("TX_DSCRP_CNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryEqualTo(String value) {
            addCriterion("TX_DSCRP_CNTRY =", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryNotEqualTo(String value) {
            addCriterion("TX_DSCRP_CNTRY <>", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryGreaterThan(String value) {
            addCriterion("TX_DSCRP_CNTRY >", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryGreaterThanOrEqualTo(String value) {
            addCriterion("TX_DSCRP_CNTRY >=", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryLessThan(String value) {
            addCriterion("TX_DSCRP_CNTRY <", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryLessThanOrEqualTo(String value) {
            addCriterion("TX_DSCRP_CNTRY <=", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryLike(String value) {
            addCriterion("TX_DSCRP_CNTRY like", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryNotLike(String value) {
            addCriterion("TX_DSCRP_CNTRY not like", value, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryIn(List<String> values) {
            addCriterion("TX_DSCRP_CNTRY in", values, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryNotIn(List<String> values) {
            addCriterion("TX_DSCRP_CNTRY not in", values, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryBetween(String value1, String value2) {
            addCriterion("TX_DSCRP_CNTRY between", value1, value2, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andTxDscrpCntryNotBetween(String value1, String value2) {
            addCriterion("TX_DSCRP_CNTRY not between", value1, value2, "txDscrpCntry");
            return (Criteria) this;
        }

        public Criteria andMerchStateIsNull() {
            addCriterion("MERCH_STATE is null");
            return (Criteria) this;
        }

        public Criteria andMerchStateIsNotNull() {
            addCriterion("MERCH_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchStateEqualTo(String value) {
            addCriterion("MERCH_STATE =", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateNotEqualTo(String value) {
            addCriterion("MERCH_STATE <>", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateGreaterThan(String value) {
            addCriterion("MERCH_STATE >", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateGreaterThanOrEqualTo(String value) {
            addCriterion("MERCH_STATE >=", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateLessThan(String value) {
            addCriterion("MERCH_STATE <", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateLessThanOrEqualTo(String value) {
            addCriterion("MERCH_STATE <=", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateLike(String value) {
            addCriterion("MERCH_STATE like", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateNotLike(String value) {
            addCriterion("MERCH_STATE not like", value, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateIn(List<String> values) {
            addCriterion("MERCH_STATE in", values, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateNotIn(List<String> values) {
            addCriterion("MERCH_STATE not in", values, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateBetween(String value1, String value2) {
            addCriterion("MERCH_STATE between", value1, value2, "merchState");
            return (Criteria) this;
        }

        public Criteria andMerchStateNotBetween(String value1, String value2) {
            addCriterion("MERCH_STATE not between", value1, value2, "merchState");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagIsNull() {
            addCriterion("DHI_POSTING_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagIsNotNull() {
            addCriterion("DHI_POSTING_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagEqualTo(String value) {
            addCriterion("DHI_POSTING_FLAG =", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagNotEqualTo(String value) {
            addCriterion("DHI_POSTING_FLAG <>", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagGreaterThan(String value) {
            addCriterion("DHI_POSTING_FLAG >", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DHI_POSTING_FLAG >=", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagLessThan(String value) {
            addCriterion("DHI_POSTING_FLAG <", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagLessThanOrEqualTo(String value) {
            addCriterion("DHI_POSTING_FLAG <=", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagLike(String value) {
            addCriterion("DHI_POSTING_FLAG like", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagNotLike(String value) {
            addCriterion("DHI_POSTING_FLAG not like", value, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagIn(List<String> values) {
            addCriterion("DHI_POSTING_FLAG in", values, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagNotIn(List<String> values) {
            addCriterion("DHI_POSTING_FLAG not in", values, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagBetween(String value1, String value2) {
            addCriterion("DHI_POSTING_FLAG between", value1, value2, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andDhiPostingFlagNotBetween(String value1, String value2) {
            addCriterion("DHI_POSTING_FLAG not between", value1, value2, "dhiPostingFlag");
            return (Criteria) this;
        }

        public Criteria andRefNmbrIsNull() {
            addCriterion("REF_NMBR is null");
            return (Criteria) this;
        }

        public Criteria andRefNmbrIsNotNull() {
            addCriterion("REF_NMBR is not null");
            return (Criteria) this;
        }

        public Criteria andRefNmbrEqualTo(String value) {
            addCriterion("REF_NMBR =", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrNotEqualTo(String value) {
            addCriterion("REF_NMBR <>", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrGreaterThan(String value) {
            addCriterion("REF_NMBR >", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrGreaterThanOrEqualTo(String value) {
            addCriterion("REF_NMBR >=", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrLessThan(String value) {
            addCriterion("REF_NMBR <", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrLessThanOrEqualTo(String value) {
            addCriterion("REF_NMBR <=", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrLike(String value) {
            addCriterion("REF_NMBR like", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrNotLike(String value) {
            addCriterion("REF_NMBR not like", value, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrIn(List<String> values) {
            addCriterion("REF_NMBR in", values, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrNotIn(List<String> values) {
            addCriterion("REF_NMBR not in", values, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrBetween(String value1, String value2) {
            addCriterion("REF_NMBR between", value1, value2, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andRefNmbrNotBetween(String value1, String value2) {
            addCriterion("REF_NMBR not between", value1, value2, "refNmbr");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgIsNull() {
            addCriterion("CHGBK_FLG is null");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgIsNotNull() {
            addCriterion("CHGBK_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgEqualTo(String value) {
            addCriterion("CHGBK_FLG =", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgNotEqualTo(String value) {
            addCriterion("CHGBK_FLG <>", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgGreaterThan(String value) {
            addCriterion("CHGBK_FLG >", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgGreaterThanOrEqualTo(String value) {
            addCriterion("CHGBK_FLG >=", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgLessThan(String value) {
            addCriterion("CHGBK_FLG <", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgLessThanOrEqualTo(String value) {
            addCriterion("CHGBK_FLG <=", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgLike(String value) {
            addCriterion("CHGBK_FLG like", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgNotLike(String value) {
            addCriterion("CHGBK_FLG not like", value, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgIn(List<String> values) {
            addCriterion("CHGBK_FLG in", values, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgNotIn(List<String> values) {
            addCriterion("CHGBK_FLG not in", values, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgBetween(String value1, String value2) {
            addCriterion("CHGBK_FLG between", value1, value2, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andChgbkFlgNotBetween(String value1, String value2) {
            addCriterion("CHGBK_FLG not between", value1, value2, "chgbkFlg");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeIsNull() {
            addCriterion("ORIG_CURR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeIsNotNull() {
            addCriterion("ORIG_CURR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeEqualTo(String value) {
            addCriterion("ORIG_CURR_CODE =", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeNotEqualTo(String value) {
            addCriterion("ORIG_CURR_CODE <>", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeGreaterThan(String value) {
            addCriterion("ORIG_CURR_CODE >", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORIG_CURR_CODE >=", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeLessThan(String value) {
            addCriterion("ORIG_CURR_CODE <", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeLessThanOrEqualTo(String value) {
            addCriterion("ORIG_CURR_CODE <=", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeLike(String value) {
            addCriterion("ORIG_CURR_CODE like", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeNotLike(String value) {
            addCriterion("ORIG_CURR_CODE not like", value, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeIn(List<String> values) {
            addCriterion("ORIG_CURR_CODE in", values, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeNotIn(List<String> values) {
            addCriterion("ORIG_CURR_CODE not in", values, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeBetween(String value1, String value2) {
            addCriterion("ORIG_CURR_CODE between", value1, value2, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrCodeNotBetween(String value1, String value2) {
            addCriterion("ORIG_CURR_CODE not between", value1, value2, "origCurrCode");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtIsNull() {
            addCriterion("ORIG_CURR_AMT is null");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtIsNotNull() {
            addCriterion("ORIG_CURR_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtEqualTo(BigDecimal value) {
            addCriterion("ORIG_CURR_AMT =", value, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtNotEqualTo(BigDecimal value) {
            addCriterion("ORIG_CURR_AMT <>", value, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtGreaterThan(BigDecimal value) {
            addCriterion("ORIG_CURR_AMT >", value, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORIG_CURR_AMT >=", value, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtLessThan(BigDecimal value) {
            addCriterion("ORIG_CURR_AMT <", value, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORIG_CURR_AMT <=", value, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtIn(List<BigDecimal> values) {
            addCriterion("ORIG_CURR_AMT in", values, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtNotIn(List<BigDecimal> values) {
            addCriterion("ORIG_CURR_AMT not in", values, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORIG_CURR_AMT between", value1, value2, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORIG_CURR_AMT not between", value1, value2, "origCurrAmt");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalIsNull() {
            addCriterion("ORIG_CURR_DECIMAL is null");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalIsNotNull() {
            addCriterion("ORIG_CURR_DECIMAL is not null");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalEqualTo(Long value) {
            addCriterion("ORIG_CURR_DECIMAL =", value, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalNotEqualTo(Long value) {
            addCriterion("ORIG_CURR_DECIMAL <>", value, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalGreaterThan(Long value) {
            addCriterion("ORIG_CURR_DECIMAL >", value, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalGreaterThanOrEqualTo(Long value) {
            addCriterion("ORIG_CURR_DECIMAL >=", value, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalLessThan(Long value) {
            addCriterion("ORIG_CURR_DECIMAL <", value, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalLessThanOrEqualTo(Long value) {
            addCriterion("ORIG_CURR_DECIMAL <=", value, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalIn(List<Long> values) {
            addCriterion("ORIG_CURR_DECIMAL in", values, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalNotIn(List<Long> values) {
            addCriterion("ORIG_CURR_DECIMAL not in", values, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalBetween(Long value1, Long value2) {
            addCriterion("ORIG_CURR_DECIMAL between", value1, value2, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOrigCurrDecimalNotBetween(Long value1, Long value2) {
            addCriterion("ORIG_CURR_DECIMAL not between", value1, value2, "origCurrDecimal");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvIsNull() {
            addCriterion("ONUS_CURR_CONV is null");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvIsNotNull() {
            addCriterion("ONUS_CURR_CONV is not null");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvEqualTo(String value) {
            addCriterion("ONUS_CURR_CONV =", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvNotEqualTo(String value) {
            addCriterion("ONUS_CURR_CONV <>", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvGreaterThan(String value) {
            addCriterion("ONUS_CURR_CONV >", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvGreaterThanOrEqualTo(String value) {
            addCriterion("ONUS_CURR_CONV >=", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvLessThan(String value) {
            addCriterion("ONUS_CURR_CONV <", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvLessThanOrEqualTo(String value) {
            addCriterion("ONUS_CURR_CONV <=", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvLike(String value) {
            addCriterion("ONUS_CURR_CONV like", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvNotLike(String value) {
            addCriterion("ONUS_CURR_CONV not like", value, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvIn(List<String> values) {
            addCriterion("ONUS_CURR_CONV in", values, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvNotIn(List<String> values) {
            addCriterion("ONUS_CURR_CONV not in", values, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvBetween(String value1, String value2) {
            addCriterion("ONUS_CURR_CONV between", value1, value2, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andOnusCurrConvNotBetween(String value1, String value2) {
            addCriterion("ONUS_CURR_CONV not between", value1, value2, "onusCurrConv");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeIsNull() {
            addCriterion("DHI_POS_MODE is null");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeIsNotNull() {
            addCriterion("DHI_POS_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeEqualTo(String value) {
            addCriterion("DHI_POS_MODE =", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeNotEqualTo(String value) {
            addCriterion("DHI_POS_MODE <>", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeGreaterThan(String value) {
            addCriterion("DHI_POS_MODE >", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeGreaterThanOrEqualTo(String value) {
            addCriterion("DHI_POS_MODE >=", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeLessThan(String value) {
            addCriterion("DHI_POS_MODE <", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeLessThanOrEqualTo(String value) {
            addCriterion("DHI_POS_MODE <=", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeLike(String value) {
            addCriterion("DHI_POS_MODE like", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeNotLike(String value) {
            addCriterion("DHI_POS_MODE not like", value, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeIn(List<String> values) {
            addCriterion("DHI_POS_MODE in", values, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeNotIn(List<String> values) {
            addCriterion("DHI_POS_MODE not in", values, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeBetween(String value1, String value2) {
            addCriterion("DHI_POS_MODE between", value1, value2, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andDhiPosModeNotBetween(String value1, String value2) {
            addCriterion("DHI_POS_MODE not between", value1, value2, "dhiPosMode");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgIsNull() {
            addCriterion("MAIL_ORDER_FLG is null");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgIsNotNull() {
            addCriterion("MAIL_ORDER_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgEqualTo(String value) {
            addCriterion("MAIL_ORDER_FLG =", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgNotEqualTo(String value) {
            addCriterion("MAIL_ORDER_FLG <>", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgGreaterThan(String value) {
            addCriterion("MAIL_ORDER_FLG >", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL_ORDER_FLG >=", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgLessThan(String value) {
            addCriterion("MAIL_ORDER_FLG <", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgLessThanOrEqualTo(String value) {
            addCriterion("MAIL_ORDER_FLG <=", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgLike(String value) {
            addCriterion("MAIL_ORDER_FLG like", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgNotLike(String value) {
            addCriterion("MAIL_ORDER_FLG not like", value, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgIn(List<String> values) {
            addCriterion("MAIL_ORDER_FLG in", values, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgNotIn(List<String> values) {
            addCriterion("MAIL_ORDER_FLG not in", values, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgBetween(String value1, String value2) {
            addCriterion("MAIL_ORDER_FLG between", value1, value2, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andMailOrderFlgNotBetween(String value1, String value2) {
            addCriterion("MAIL_ORDER_FLG not between", value1, value2, "mailOrderFlg");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoIsNull() {
            addCriterion("CMBI_MERCH_NO is null");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoIsNotNull() {
            addCriterion("CMBI_MERCH_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO =", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO <>", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoGreaterThan(String value) {
            addCriterion("CMBI_MERCH_NO >", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoGreaterThanOrEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO >=", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoLessThan(String value) {
            addCriterion("CMBI_MERCH_NO <", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoLessThanOrEqualTo(String value) {
            addCriterion("CMBI_MERCH_NO <=", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoLike(String value) {
            addCriterion("CMBI_MERCH_NO like", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotLike(String value) {
            addCriterion("CMBI_MERCH_NO not like", value, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoIn(List<String> values) {
            addCriterion("CMBI_MERCH_NO in", values, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotIn(List<String> values) {
            addCriterion("CMBI_MERCH_NO not in", values, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoBetween(String value1, String value2) {
            addCriterion("CMBI_MERCH_NO between", value1, value2, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andCmbiMerchNoNotBetween(String value1, String value2) {
            addCriterion("CMBI_MERCH_NO not between", value1, value2, "cmbiMerchNo");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndIsNull() {
            addCriterion("DHI_INSTALLMENT_IND is null");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndIsNotNull() {
            addCriterion("DHI_INSTALLMENT_IND is not null");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndEqualTo(String value) {
            addCriterion("DHI_INSTALLMENT_IND =", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndNotEqualTo(String value) {
            addCriterion("DHI_INSTALLMENT_IND <>", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndGreaterThan(String value) {
            addCriterion("DHI_INSTALLMENT_IND >", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndGreaterThanOrEqualTo(String value) {
            addCriterion("DHI_INSTALLMENT_IND >=", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndLessThan(String value) {
            addCriterion("DHI_INSTALLMENT_IND <", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndLessThanOrEqualTo(String value) {
            addCriterion("DHI_INSTALLMENT_IND <=", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndLike(String value) {
            addCriterion("DHI_INSTALLMENT_IND like", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndNotLike(String value) {
            addCriterion("DHI_INSTALLMENT_IND not like", value, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndIn(List<String> values) {
            addCriterion("DHI_INSTALLMENT_IND in", values, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndNotIn(List<String> values) {
            addCriterion("DHI_INSTALLMENT_IND not in", values, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndBetween(String value1, String value2) {
            addCriterion("DHI_INSTALLMENT_IND between", value1, value2, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andDhiInstallmentIndNotBetween(String value1, String value2) {
            addCriterion("DHI_INSTALLMENT_IND not between", value1, value2, "dhiInstallmentInd");
            return (Criteria) this;
        }

        public Criteria andTradChanelIsNull() {
            addCriterion("TRAD_CHANEL is null");
            return (Criteria) this;
        }

        public Criteria andTradChanelIsNotNull() {
            addCriterion("TRAD_CHANEL is not null");
            return (Criteria) this;
        }

        public Criteria andTradChanelEqualTo(String value) {
            addCriterion("TRAD_CHANEL =", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelNotEqualTo(String value) {
            addCriterion("TRAD_CHANEL <>", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelGreaterThan(String value) {
            addCriterion("TRAD_CHANEL >", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelGreaterThanOrEqualTo(String value) {
            addCriterion("TRAD_CHANEL >=", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelLessThan(String value) {
            addCriterion("TRAD_CHANEL <", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelLessThanOrEqualTo(String value) {
            addCriterion("TRAD_CHANEL <=", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelLike(String value) {
            addCriterion("TRAD_CHANEL like", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelNotLike(String value) {
            addCriterion("TRAD_CHANEL not like", value, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelIn(List<String> values) {
            addCriterion("TRAD_CHANEL in", values, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelNotIn(List<String> values) {
            addCriterion("TRAD_CHANEL not in", values, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelBetween(String value1, String value2) {
            addCriterion("TRAD_CHANEL between", value1, value2, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTradChanelNotBetween(String value1, String value2) {
            addCriterion("TRAD_CHANEL not between", value1, value2, "tradChanel");
            return (Criteria) this;
        }

        public Criteria andTxTypeIsNull() {
            addCriterion("TX_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTxTypeIsNotNull() {
            addCriterion("TX_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTxTypeEqualTo(String value) {
            addCriterion("TX_TYPE =", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeNotEqualTo(String value) {
            addCriterion("TX_TYPE <>", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeGreaterThan(String value) {
            addCriterion("TX_TYPE >", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TX_TYPE >=", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeLessThan(String value) {
            addCriterion("TX_TYPE <", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeLessThanOrEqualTo(String value) {
            addCriterion("TX_TYPE <=", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeLike(String value) {
            addCriterion("TX_TYPE like", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeNotLike(String value) {
            addCriterion("TX_TYPE not like", value, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeIn(List<String> values) {
            addCriterion("TX_TYPE in", values, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeNotIn(List<String> values) {
            addCriterion("TX_TYPE not in", values, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeBetween(String value1, String value2) {
            addCriterion("TX_TYPE between", value1, value2, "txType");
            return (Criteria) this;
        }

        public Criteria andTxTypeNotBetween(String value1, String value2) {
            addCriterion("TX_TYPE not between", value1, value2, "txType");
            return (Criteria) this;
        }

        public Criteria andTxCdNewIsNull() {
            addCriterion("TX_CD_NEW is null");
            return (Criteria) this;
        }

        public Criteria andTxCdNewIsNotNull() {
            addCriterion("TX_CD_NEW is not null");
            return (Criteria) this;
        }

        public Criteria andTxCdNewEqualTo(String value) {
            addCriterion("TX_CD_NEW =", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewNotEqualTo(String value) {
            addCriterion("TX_CD_NEW <>", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewGreaterThan(String value) {
            addCriterion("TX_CD_NEW >", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewGreaterThanOrEqualTo(String value) {
            addCriterion("TX_CD_NEW >=", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewLessThan(String value) {
            addCriterion("TX_CD_NEW <", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewLessThanOrEqualTo(String value) {
            addCriterion("TX_CD_NEW <=", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewLike(String value) {
            addCriterion("TX_CD_NEW like", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewNotLike(String value) {
            addCriterion("TX_CD_NEW not like", value, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewIn(List<String> values) {
            addCriterion("TX_CD_NEW in", values, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewNotIn(List<String> values) {
            addCriterion("TX_CD_NEW not in", values, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewBetween(String value1, String value2) {
            addCriterion("TX_CD_NEW between", value1, value2, "txCdNew");
            return (Criteria) this;
        }

        public Criteria andTxCdNewNotBetween(String value1, String value2) {
            addCriterion("TX_CD_NEW not between", value1, value2, "txCdNew");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}