package org.fbi.gwk.repository.model.gwk;

import java.math.BigDecimal;

public class OdsbCrdCrtTrad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.ACTP
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String actp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.CRD_TYP
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String crdTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.CRD_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String crdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.TX_DAY
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String txDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.TX_CD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String txCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.INAC_AMT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private BigDecimal inacAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.INAC_DATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String inacDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.SRC_CD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String srcCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.DHI_AUTH_CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String dhiAuthCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.REF_DATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String refDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.REF_BATCH_ID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String refBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.REF_SEQ_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String refSeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.MERCHANT_ORG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String merchantOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.DHI_MERCH_ACCT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String dhiMerchAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.MERCHANT_KND_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String merchantKndNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.FILLER_2
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String filler2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.FILLER_3
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String filler3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.TX_DSCRP_CNTRY
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String txDscrpCntry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.MERCH_STATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String merchState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.DHI_POSTING_FLAG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String dhiPostingFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.REF_NMBR
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String refNmbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.CHGBK_FLG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String chgbkFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String origCurrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_AMT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private BigDecimal origCurrAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_DECIMAL
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private Long origCurrDecimal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.ONUS_CURR_CONV
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String onusCurrConv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.DHI_POS_MODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String dhiPosMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.MAIL_ORDER_FLG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String mailOrderFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.CMBI_MERCH_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String cmbiMerchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.DHI_INSTALLMENT_IND
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String dhiInstallmentInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.TRAD_CHANEL
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String tradChanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.TX_TYPE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String txType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GWK.ODSB_CRD_CRT_TRAD.TX_CD_NEW
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    private String txCdNew;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.ACTP
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.ACTP
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getActp() {
        return actp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.ACTP
     *
     * @param actp the value for GWK.ODSB_CRD_CRT_TRAD.ACTP
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setActp(String actp) {
        this.actp = actp == null ? null : actp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.CRD_TYP
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.CRD_TYP
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getCrdTyp() {
        return crdTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.CRD_TYP
     *
     * @param crdTyp the value for GWK.ODSB_CRD_CRT_TRAD.CRD_TYP
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCrdTyp(String crdTyp) {
        this.crdTyp = crdTyp == null ? null : crdTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.CRD_NO
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.CRD_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getCrdNo() {
        return crdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.CRD_NO
     *
     * @param crdNo the value for GWK.ODSB_CRD_CRT_TRAD.CRD_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCrdNo(String crdNo) {
        this.crdNo = crdNo == null ? null : crdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_DAY
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.TX_DAY
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getTxDay() {
        return txDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_DAY
     *
     * @param txDay the value for GWK.ODSB_CRD_CRT_TRAD.TX_DAY
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setTxDay(String txDay) {
        this.txDay = txDay == null ? null : txDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_CD
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.TX_CD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getTxCd() {
        return txCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_CD
     *
     * @param txCd the value for GWK.ODSB_CRD_CRT_TRAD.TX_CD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setTxCd(String txCd) {
        this.txCd = txCd == null ? null : txCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.INAC_AMT
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.INAC_AMT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public BigDecimal getInacAmt() {
        return inacAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.INAC_AMT
     *
     * @param inacAmt the value for GWK.ODSB_CRD_CRT_TRAD.INAC_AMT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setInacAmt(BigDecimal inacAmt) {
        this.inacAmt = inacAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.INAC_DATE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.INAC_DATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getInacDate() {
        return inacDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.INAC_DATE
     *
     * @param inacDate the value for GWK.ODSB_CRD_CRT_TRAD.INAC_DATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setInacDate(String inacDate) {
        this.inacDate = inacDate == null ? null : inacDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.SRC_CD
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.SRC_CD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getSrcCd() {
        return srcCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.SRC_CD
     *
     * @param srcCd the value for GWK.ODSB_CRD_CRT_TRAD.SRC_CD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setSrcCd(String srcCd) {
        this.srcCd = srcCd == null ? null : srcCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_AUTH_CODE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.DHI_AUTH_CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getDhiAuthCode() {
        return dhiAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_AUTH_CODE
     *
     * @param dhiAuthCode the value for GWK.ODSB_CRD_CRT_TRAD.DHI_AUTH_CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDhiAuthCode(String dhiAuthCode) {
        this.dhiAuthCode = dhiAuthCode == null ? null : dhiAuthCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_DATE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.REF_DATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getRefDate() {
        return refDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_DATE
     *
     * @param refDate the value for GWK.ODSB_CRD_CRT_TRAD.REF_DATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setRefDate(String refDate) {
        this.refDate = refDate == null ? null : refDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_BATCH_ID
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.REF_BATCH_ID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getRefBatchId() {
        return refBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_BATCH_ID
     *
     * @param refBatchId the value for GWK.ODSB_CRD_CRT_TRAD.REF_BATCH_ID
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setRefBatchId(String refBatchId) {
        this.refBatchId = refBatchId == null ? null : refBatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_SEQ_NO
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.REF_SEQ_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getRefSeqNo() {
        return refSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_SEQ_NO
     *
     * @param refSeqNo the value for GWK.ODSB_CRD_CRT_TRAD.REF_SEQ_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setRefSeqNo(String refSeqNo) {
        this.refSeqNo = refSeqNo == null ? null : refSeqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.MERCHANT_ORG
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.MERCHANT_ORG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getMerchantOrg() {
        return merchantOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.MERCHANT_ORG
     *
     * @param merchantOrg the value for GWK.ODSB_CRD_CRT_TRAD.MERCHANT_ORG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setMerchantOrg(String merchantOrg) {
        this.merchantOrg = merchantOrg == null ? null : merchantOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_MERCH_ACCT
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.DHI_MERCH_ACCT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getDhiMerchAcct() {
        return dhiMerchAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_MERCH_ACCT
     *
     * @param dhiMerchAcct the value for GWK.ODSB_CRD_CRT_TRAD.DHI_MERCH_ACCT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDhiMerchAcct(String dhiMerchAcct) {
        this.dhiMerchAcct = dhiMerchAcct == null ? null : dhiMerchAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.MERCHANT_KND_NO
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.MERCHANT_KND_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getMerchantKndNo() {
        return merchantKndNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.MERCHANT_KND_NO
     *
     * @param merchantKndNo the value for GWK.ODSB_CRD_CRT_TRAD.MERCHANT_KND_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setMerchantKndNo(String merchantKndNo) {
        this.merchantKndNo = merchantKndNo == null ? null : merchantKndNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.FILLER_2
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.FILLER_2
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getFiller2() {
        return filler2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.FILLER_2
     *
     * @param filler2 the value for GWK.ODSB_CRD_CRT_TRAD.FILLER_2
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setFiller2(String filler2) {
        this.filler2 = filler2 == null ? null : filler2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.FILLER_3
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.FILLER_3
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.FILLER_3
     *
     * @param filler3 the value for GWK.ODSB_CRD_CRT_TRAD.FILLER_3
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setFiller3(String filler3) {
        this.filler3 = filler3 == null ? null : filler3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_DSCRP_CNTRY
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.TX_DSCRP_CNTRY
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getTxDscrpCntry() {
        return txDscrpCntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_DSCRP_CNTRY
     *
     * @param txDscrpCntry the value for GWK.ODSB_CRD_CRT_TRAD.TX_DSCRP_CNTRY
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setTxDscrpCntry(String txDscrpCntry) {
        this.txDscrpCntry = txDscrpCntry == null ? null : txDscrpCntry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.MERCH_STATE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.MERCH_STATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getMerchState() {
        return merchState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.MERCH_STATE
     *
     * @param merchState the value for GWK.ODSB_CRD_CRT_TRAD.MERCH_STATE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setMerchState(String merchState) {
        this.merchState = merchState == null ? null : merchState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_POSTING_FLAG
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.DHI_POSTING_FLAG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getDhiPostingFlag() {
        return dhiPostingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_POSTING_FLAG
     *
     * @param dhiPostingFlag the value for GWK.ODSB_CRD_CRT_TRAD.DHI_POSTING_FLAG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDhiPostingFlag(String dhiPostingFlag) {
        this.dhiPostingFlag = dhiPostingFlag == null ? null : dhiPostingFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_NMBR
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.REF_NMBR
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getRefNmbr() {
        return refNmbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.REF_NMBR
     *
     * @param refNmbr the value for GWK.ODSB_CRD_CRT_TRAD.REF_NMBR
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setRefNmbr(String refNmbr) {
        this.refNmbr = refNmbr == null ? null : refNmbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.CHGBK_FLG
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.CHGBK_FLG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getChgbkFlg() {
        return chgbkFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.CHGBK_FLG
     *
     * @param chgbkFlg the value for GWK.ODSB_CRD_CRT_TRAD.CHGBK_FLG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setChgbkFlg(String chgbkFlg) {
        this.chgbkFlg = chgbkFlg == null ? null : chgbkFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_CODE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOrigCurrCode() {
        return origCurrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_CODE
     *
     * @param origCurrCode the value for GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_CODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrigCurrCode(String origCurrCode) {
        this.origCurrCode = origCurrCode == null ? null : origCurrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_AMT
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_AMT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public BigDecimal getOrigCurrAmt() {
        return origCurrAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_AMT
     *
     * @param origCurrAmt the value for GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_AMT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrigCurrAmt(BigDecimal origCurrAmt) {
        this.origCurrAmt = origCurrAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_DECIMAL
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_DECIMAL
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public Long getOrigCurrDecimal() {
        return origCurrDecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_DECIMAL
     *
     * @param origCurrDecimal the value for GWK.ODSB_CRD_CRT_TRAD.ORIG_CURR_DECIMAL
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOrigCurrDecimal(Long origCurrDecimal) {
        this.origCurrDecimal = origCurrDecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.ONUS_CURR_CONV
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.ONUS_CURR_CONV
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getOnusCurrConv() {
        return onusCurrConv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.ONUS_CURR_CONV
     *
     * @param onusCurrConv the value for GWK.ODSB_CRD_CRT_TRAD.ONUS_CURR_CONV
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setOnusCurrConv(String onusCurrConv) {
        this.onusCurrConv = onusCurrConv == null ? null : onusCurrConv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_POS_MODE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.DHI_POS_MODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getDhiPosMode() {
        return dhiPosMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_POS_MODE
     *
     * @param dhiPosMode the value for GWK.ODSB_CRD_CRT_TRAD.DHI_POS_MODE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDhiPosMode(String dhiPosMode) {
        this.dhiPosMode = dhiPosMode == null ? null : dhiPosMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.MAIL_ORDER_FLG
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.MAIL_ORDER_FLG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getMailOrderFlg() {
        return mailOrderFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.MAIL_ORDER_FLG
     *
     * @param mailOrderFlg the value for GWK.ODSB_CRD_CRT_TRAD.MAIL_ORDER_FLG
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setMailOrderFlg(String mailOrderFlg) {
        this.mailOrderFlg = mailOrderFlg == null ? null : mailOrderFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.CMBI_MERCH_NO
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.CMBI_MERCH_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getCmbiMerchNo() {
        return cmbiMerchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.CMBI_MERCH_NO
     *
     * @param cmbiMerchNo the value for GWK.ODSB_CRD_CRT_TRAD.CMBI_MERCH_NO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setCmbiMerchNo(String cmbiMerchNo) {
        this.cmbiMerchNo = cmbiMerchNo == null ? null : cmbiMerchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_INSTALLMENT_IND
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.DHI_INSTALLMENT_IND
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getDhiInstallmentInd() {
        return dhiInstallmentInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.DHI_INSTALLMENT_IND
     *
     * @param dhiInstallmentInd the value for GWK.ODSB_CRD_CRT_TRAD.DHI_INSTALLMENT_IND
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setDhiInstallmentInd(String dhiInstallmentInd) {
        this.dhiInstallmentInd = dhiInstallmentInd == null ? null : dhiInstallmentInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.TRAD_CHANEL
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.TRAD_CHANEL
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getTradChanel() {
        return tradChanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.TRAD_CHANEL
     *
     * @param tradChanel the value for GWK.ODSB_CRD_CRT_TRAD.TRAD_CHANEL
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setTradChanel(String tradChanel) {
        this.tradChanel = tradChanel == null ? null : tradChanel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_TYPE
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.TX_TYPE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getTxType() {
        return txType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_TYPE
     *
     * @param txType the value for GWK.ODSB_CRD_CRT_TRAD.TX_TYPE
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setTxType(String txType) {
        this.txType = txType == null ? null : txType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_CD_NEW
     *
     * @return the value of GWK.ODSB_CRD_CRT_TRAD.TX_CD_NEW
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public String getTxCdNew() {
        return txCdNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GWK.ODSB_CRD_CRT_TRAD.TX_CD_NEW
     *
     * @param txCdNew the value for GWK.ODSB_CRD_CRT_TRAD.TX_CD_NEW
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    public void setTxCdNew(String txCdNew) {
        this.txCdNew = txCdNew == null ? null : txCdNew.trim();
    }
}