package org.fbi.gwk.repository.dao.gwk;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.gwk.repository.model.gwk.LsCardstatus;
import org.fbi.gwk.repository.model.gwk.LsCardstatusExample;

public interface LsCardstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int countByExample(LsCardstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByExample(LsCardstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insert(LsCardstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insertSelective(LsCardstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    List<LsCardstatus> selectByExample(LsCardstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") LsCardstatus record, @Param("example") LsCardstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_CARDSTATUS
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExample(@Param("record") LsCardstatus record, @Param("example") LsCardstatusExample example);
}