package org.fbi.gwk.repository.dao.gwk;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.gwk.repository.model.gwk.LsPersonalinfo;
import org.fbi.gwk.repository.model.gwk.LsPersonalinfoExample;

public interface LsPersonalinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int countByExample(LsPersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByExample(LsPersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByPrimaryKey(String recinsequence);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insert(LsPersonalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insertSelective(LsPersonalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    List<LsPersonalinfo> selectByExample(LsPersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    LsPersonalinfo selectByPrimaryKey(String recinsequence);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") LsPersonalinfo record, @Param("example") LsPersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExample(@Param("record") LsPersonalinfo record, @Param("example") LsPersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByPrimaryKeySelective(LsPersonalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_PERSONALINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByPrimaryKey(LsPersonalinfo record);
}