package org.fbi.gwk.repository.dao.gwk;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.gwk.repository.model.gwk.LsSysinfo;
import org.fbi.gwk.repository.model.gwk.LsSysinfoExample;

public interface LsSysinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int countByExample(LsSysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByExample(LsSysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insert(LsSysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insertSelective(LsSysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    List<LsSysinfo> selectByExample(LsSysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") LsSysinfo record, @Param("example") LsSysinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.LS_SYSINFO
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExample(@Param("record") LsSysinfo record, @Param("example") LsSysinfoExample example);
}