package org.fbi.gwk.repository.dao.gwk;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.gwk.repository.model.gwk.OdsbCrdCrt;
import org.fbi.gwk.repository.model.gwk.OdsbCrdCrtExample;

public interface OdsbCrdCrtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int countByExample(OdsbCrdCrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByExample(OdsbCrdCrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByPrimaryKey(String crdNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insert(OdsbCrdCrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insertSelective(OdsbCrdCrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    List<OdsbCrdCrt> selectByExample(OdsbCrdCrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    OdsbCrdCrt selectByPrimaryKey(String crdNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") OdsbCrdCrt record, @Param("example") OdsbCrdCrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExample(@Param("record") OdsbCrdCrt record, @Param("example") OdsbCrdCrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByPrimaryKeySelective(OdsbCrdCrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByPrimaryKey(OdsbCrdCrt record);
}