package org.fbi.gwk.repository.dao.gwk;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.gwk.repository.model.gwk.OdsbCrdCrtTrad;
import org.fbi.gwk.repository.model.gwk.OdsbCrdCrtTradExample;

public interface OdsbCrdCrtTradMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int countByExample(OdsbCrdCrtTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int deleteByExample(OdsbCrdCrtTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insert(OdsbCrdCrtTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int insertSelective(OdsbCrdCrtTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    List<OdsbCrdCrtTrad> selectByExample(OdsbCrdCrtTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") OdsbCrdCrtTrad record, @Param("example") OdsbCrdCrtTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GWK.ODSB_CRD_CRT_TRAD
     *
     * @mbggenerated Mon Mar 09 17:29:36 CST 2015
     */
    int updateByExample(@Param("record") OdsbCrdCrtTrad record, @Param("example") OdsbCrdCrtTradExample example);
}